/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface AdditionalAllocationData
 */
export interface AdditionalAllocationData {
  /**
   * @memberof AdditionalAllocationData
   * @type {boolean}
   */
  roadcaptain?: boolean;
}

/** Check if a given object implements the AdditionalAllocationData interface. */
export function instanceOfAdditionalAllocationData(
  value: object
): value is AdditionalAllocationData {
  return true;
}

export function AdditionalAllocationDataFromJSON(
  json: any
): AdditionalAllocationData {
  return AdditionalAllocationDataFromJSONTyped(json, false);
}

export function AdditionalAllocationDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AdditionalAllocationData {
  if (json == null) {
    return json;
  }
  return {
    roadcaptain: json['roadcaptain'] == null ? undefined : json['roadcaptain']
  };
}

export function AdditionalAllocationDataToJSON(
  json: any
): AdditionalAllocationData {
  return AdditionalAllocationDataToJSONTyped(json, false);
}

export function AdditionalAllocationDataToJSONTyped(
  value?: AdditionalAllocationData | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    roadcaptain: value['roadcaptain']
  };
}
