/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface AllocationTypesAllocationTypesInner
 */
export interface AllocationTypesAllocationTypesInner {
  /**
   * @memberof AllocationTypesAllocationTypesInner
   * @type {number}
   */
  id?: number | null;
  /**
   * @memberof AllocationTypesAllocationTypesInner
   * @type {string}
   */
  name?: string;
  /**
   * @memberof AllocationTypesAllocationTypesInner
   * @type {string}
   */
  label?: string;
  /**
   * @memberof AllocationTypesAllocationTypesInner
   * @type {string}
   */
  slug?: string;
  /**
   * @memberof AllocationTypesAllocationTypesInner
   * @type {Date}
   */
  start?: Date | null;
  /**
   * @memberof AllocationTypesAllocationTypesInner
   * @type {Date}
   */
  end?: Date | null;
}

/**
 * Check if a given object implements the AllocationTypesAllocationTypesInner
 * interface.
 */
export function instanceOfAllocationTypesAllocationTypesInner(
  value: object
): value is AllocationTypesAllocationTypesInner {
  return true;
}

export function AllocationTypesAllocationTypesInnerFromJSON(
  json: any
): AllocationTypesAllocationTypesInner {
  return AllocationTypesAllocationTypesInnerFromJSONTyped(json, false);
}

export function AllocationTypesAllocationTypesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AllocationTypesAllocationTypesInner {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    label: json['label'] == null ? undefined : json['label'],
    slug: json['slug'] == null ? undefined : json['slug'],
    start: json['start'] == null ? undefined : new Date(json['start']),
    end: json['end'] == null ? undefined : new Date(json['end'])
  };
}

export function AllocationTypesAllocationTypesInnerToJSON(
  json: any
): AllocationTypesAllocationTypesInner {
  return AllocationTypesAllocationTypesInnerToJSONTyped(json, false);
}

export function AllocationTypesAllocationTypesInnerToJSONTyped(
  value?: AllocationTypesAllocationTypesInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    label: value['label'],
    slug: value['slug'],
    start:
      value['start'] == null
        ? undefined
        : (value['start'] as any).toISOString(),
    end: value['end'] == null ? undefined : (value['end'] as any).toISOString()
  };
}
