/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface AnnouncementStatusBody
 */
export interface AnnouncementStatusBody {
  /**
   * @memberof AnnouncementStatusBody
   * @type {string}
   */
  status: AnnouncementStatusBodyStatusEnum;
}

/** @export */
export const AnnouncementStatusBodyStatusEnum = {
  ReadAt: 'read_at',
  Retrieved: 'retrieved',
  Opened: 'opened',
  ScrolledDown: 'scrolled_down',
  OpenedAttachment: 'opened_attachment',
  ConfirmedMessagesRead: 'confirmed_messages_read'
} as const;
export type AnnouncementStatusBodyStatusEnum =
  (typeof AnnouncementStatusBodyStatusEnum)[keyof typeof AnnouncementStatusBodyStatusEnum];

/** Check if a given object implements the AnnouncementStatusBody interface. */
export function instanceOfAnnouncementStatusBody(
  value: object
): value is AnnouncementStatusBody {
  if (!('status' in value) || value['status'] === undefined) return false;
  return true;
}

export function AnnouncementStatusBodyFromJSON(
  json: any
): AnnouncementStatusBody {
  return AnnouncementStatusBodyFromJSONTyped(json, false);
}

export function AnnouncementStatusBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnnouncementStatusBody {
  if (json == null) {
    return json;
  }
  return {
    status: json['status']
  };
}

export function AnnouncementStatusBodyToJSON(
  json: any
): AnnouncementStatusBody {
  return AnnouncementStatusBodyToJSONTyped(json, false);
}

export function AnnouncementStatusBodyToJSONTyped(
  value?: AnnouncementStatusBody | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value['status']
  };
}
