/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaResource } from './MediaResource';
import {
  MediaResourceFromJSON,
  MediaResourceFromJSONTyped,
  MediaResourceToJSON,
  MediaResourceToJSONTyped
} from './MediaResource';

/**
 * @export
 * @interface AnnouncementCategoryResource
 */
export interface AnnouncementCategoryResource {
  /**
   * @memberof AnnouncementCategoryResource
   * @type {number}
   */
  id?: number;
  /**
   * @memberof AnnouncementCategoryResource
   * @type {string}
   */
  name?: string;
  /**
   * @memberof AnnouncementCategoryResource
   * @type {MediaResource}
   */
  icon?: MediaResource;
  /**
   * @memberof AnnouncementCategoryResource
   * @type {Date}
   */
  createdAt?: Date;
  /**
   * @memberof AnnouncementCategoryResource
   * @type {Date}
   */
  updatedAt?: Date;
}

/**
 * Check if a given object implements the AnnouncementCategoryResource
 * interface.
 */
export function instanceOfAnnouncementCategoryResource(
  value: object
): value is AnnouncementCategoryResource {
  return true;
}

export function AnnouncementCategoryResourceFromJSON(
  json: any
): AnnouncementCategoryResource {
  return AnnouncementCategoryResourceFromJSONTyped(json, false);
}

export function AnnouncementCategoryResourceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnnouncementCategoryResource {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    icon:
      json['icon'] == null ? undefined : MediaResourceFromJSON(json['icon']),
    createdAt:
      json['created_at'] == null ? undefined : new Date(json['created_at']),
    updatedAt:
      json['updated_at'] == null ? undefined : new Date(json['updated_at'])
  };
}

export function AnnouncementCategoryResourceToJSON(
  json: any
): AnnouncementCategoryResource {
  return AnnouncementCategoryResourceToJSONTyped(json, false);
}

export function AnnouncementCategoryResourceToJSONTyped(
  value?: AnnouncementCategoryResource | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    icon: MediaResourceToJSON(value['icon']),
    created_at:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updated_at:
      value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString()
  };
}
