/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface AuthConfigurationEndpoints
 */
export interface AuthConfigurationEndpoints {
  /**
   * @memberof AuthConfigurationEndpoints
   * @type {string}
   */
  authorizationEndpoint?: string;
  /**
   * @memberof AuthConfigurationEndpoints
   * @type {string}
   */
  tokenEndpoint?: string;
  /**
   * @memberof AuthConfigurationEndpoints
   * @type {string}
   */
  userinfoEndpoint?: string | null;
  /**
   * @memberof AuthConfigurationEndpoints
   * @type {string}
   */
  jwksUri?: string;
  /**
   * @memberof AuthConfigurationEndpoints
   * @type {string}
   */
  endSessionEndpoint?: string | null;
  /**
   * @memberof AuthConfigurationEndpoints
   * @type {string}
   */
  introspectionEndpoint?: string | null;
  /**
   * @memberof AuthConfigurationEndpoints
   * @type {string}
   */
  revocationEndpoint?: string | null;
}

/** Check if a given object implements the AuthConfigurationEndpoints interface. */
export function instanceOfAuthConfigurationEndpoints(
  value: object
): value is AuthConfigurationEndpoints {
  return true;
}

export function AuthConfigurationEndpointsFromJSON(
  json: any
): AuthConfigurationEndpoints {
  return AuthConfigurationEndpointsFromJSONTyped(json, false);
}

export function AuthConfigurationEndpointsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthConfigurationEndpoints {
  if (json == null) {
    return json;
  }
  return {
    authorizationEndpoint:
      json['authorization_endpoint'] == null
        ? undefined
        : json['authorization_endpoint'],
    tokenEndpoint:
      json['token_endpoint'] == null ? undefined : json['token_endpoint'],
    userinfoEndpoint:
      json['userinfo_endpoint'] == null ? undefined : json['userinfo_endpoint'],
    jwksUri: json['jwks_uri'] == null ? undefined : json['jwks_uri'],
    endSessionEndpoint:
      json['end_session_endpoint'] == null
        ? undefined
        : json['end_session_endpoint'],
    introspectionEndpoint:
      json['introspection_endpoint'] == null
        ? undefined
        : json['introspection_endpoint'],
    revocationEndpoint:
      json['revocation_endpoint'] == null
        ? undefined
        : json['revocation_endpoint']
  };
}

export function AuthConfigurationEndpointsToJSON(
  json: any
): AuthConfigurationEndpoints {
  return AuthConfigurationEndpointsToJSONTyped(json, false);
}

export function AuthConfigurationEndpointsToJSONTyped(
  value?: AuthConfigurationEndpoints | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    authorization_endpoint: value['authorizationEndpoint'],
    token_endpoint: value['tokenEndpoint'],
    userinfo_endpoint: value['userinfoEndpoint'],
    jwks_uri: value['jwksUri'],
    end_session_endpoint: value['endSessionEndpoint'],
    introspection_endpoint: value['introspectionEndpoint'],
    revocation_endpoint: value['revocationEndpoint']
  };
}
