/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthConfiguration } from './AuthConfiguration';
import {
  AuthConfigurationFromJSON,
  AuthConfigurationFromJSONTyped,
  AuthConfigurationToJSON,
  AuthConfigurationToJSONTyped
} from './AuthConfiguration';

/**
 * @export
 * @interface AuthConfigurationsGet200Response
 */
export interface AuthConfigurationsGet200Response {
  /**
   * @memberof AuthConfigurationsGet200Response
   * @type {AuthConfiguration[]}
   */
  data?: Array<AuthConfiguration>;
}

/**
 * Check if a given object implements the AuthConfigurationsGet200Response
 * interface.
 */
export function instanceOfAuthConfigurationsGet200Response(
  value: object
): value is AuthConfigurationsGet200Response {
  return true;
}

export function AuthConfigurationsGet200ResponseFromJSON(
  json: any
): AuthConfigurationsGet200Response {
  return AuthConfigurationsGet200ResponseFromJSONTyped(json, false);
}

export function AuthConfigurationsGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthConfigurationsGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(AuthConfigurationFromJSON)
  };
}

export function AuthConfigurationsGet200ResponseToJSON(
  json: any
): AuthConfigurationsGet200Response {
  return AuthConfigurationsGet200ResponseToJSONTyped(json, false);
}

export function AuthConfigurationsGet200ResponseToJSONTyped(
  value?: AuthConfigurationsGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(AuthConfigurationToJSON)
  };
}
