/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface AuthConfigurationButtonLabels
 */
export interface AuthConfigurationButtonLabels {
  /**
   * @memberof AuthConfigurationButtonLabels
   * @type {string}
   */
  en?: string;
  /**
   * @memberof AuthConfigurationButtonLabels
   * @type {string}
   */
  nl?: string;
}

/**
 * Check if a given object implements the AuthConfigurationButtonLabels
 * interface.
 */
export function instanceOfAuthConfigurationButtonLabels(
  value: object
): value is AuthConfigurationButtonLabels {
  return true;
}

export function AuthConfigurationButtonLabelsFromJSON(
  json: any
): AuthConfigurationButtonLabels {
  return AuthConfigurationButtonLabelsFromJSONTyped(json, false);
}

export function AuthConfigurationButtonLabelsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthConfigurationButtonLabels {
  if (json == null) {
    return json;
  }
  return {
    en: json['en'] == null ? undefined : json['en'],
    nl: json['nl'] == null ? undefined : json['nl']
  };
}

export function AuthConfigurationButtonLabelsToJSON(
  json: any
): AuthConfigurationButtonLabels {
  return AuthConfigurationButtonLabelsToJSONTyped(json, false);
}

export function AuthConfigurationButtonLabelsToJSONTyped(
  value?: AuthConfigurationButtonLabels | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    en: value['en'],
    nl: value['nl']
  };
}
