/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface DatasourceProjectWithoutAllocationTypes
 */
export interface DatasourceProjectWithoutAllocationTypes {
  /**
   * @memberof DatasourceProjectWithoutAllocationTypes
   * @type {number}
   */
  id?: number;
  /**
   * @memberof DatasourceProjectWithoutAllocationTypes
   * @type {number}
   */
  datasourceId?: number | null;
  /**
   * Use this field to display to the user
   *
   * @memberof DatasourceProjectWithoutAllocationTypes
   * @type {string}
   */
  label?: string;
  /**
   * @memberof DatasourceProjectWithoutAllocationTypes
   * @type {string}
   */
  name?: string;
  /**
   * @memberof DatasourceProjectWithoutAllocationTypes
   * @type {Date}
   */
  start?: Date;
  /**
   * @memberof DatasourceProjectWithoutAllocationTypes
   * @type {Date}
   */
  end?: Date;
  /**
   * @memberof DatasourceProjectWithoutAllocationTypes
   * @type {string}
   */
  color?: string;
  /**
   * @memberof DatasourceProjectWithoutAllocationTypes
   * @type {object}
   */
  extraData?: object | null;
}

/**
 * Check if a given object implements the
 * DatasourceProjectWithoutAllocationTypes interface.
 */
export function instanceOfDatasourceProjectWithoutAllocationTypes(
  value: object
): value is DatasourceProjectWithoutAllocationTypes {
  return true;
}

export function DatasourceProjectWithoutAllocationTypesFromJSON(
  json: any
): DatasourceProjectWithoutAllocationTypes {
  return DatasourceProjectWithoutAllocationTypesFromJSONTyped(json, false);
}

export function DatasourceProjectWithoutAllocationTypesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DatasourceProjectWithoutAllocationTypes {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    datasourceId:
      json['datasource_id'] == null ? undefined : json['datasource_id'],
    label: json['label'] == null ? undefined : json['label'],
    name: json['name'] == null ? undefined : json['name'],
    start: json['start'] == null ? undefined : new Date(json['start']),
    end: json['end'] == null ? undefined : new Date(json['end']),
    color: json['color'] == null ? undefined : json['color'],
    extraData: json['extra_data'] == null ? undefined : json['extra_data']
  };
}

export function DatasourceProjectWithoutAllocationTypesToJSON(
  json: any
): DatasourceProjectWithoutAllocationTypes {
  return DatasourceProjectWithoutAllocationTypesToJSONTyped(json, false);
}

export function DatasourceProjectWithoutAllocationTypesToJSONTyped(
  value?: DatasourceProjectWithoutAllocationTypes | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    datasource_id: value['datasourceId'],
    label: value['label'],
    name: value['name'],
    start: value['start'] == null ? undefined : value['start'].toISOString(),
    end: value['end'] == null ? undefined : value['end'].toISOString(),
    color: value['color'],
    extra_data: value['extraData']
  };
}
