/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { AdditionalAllocationData } from './AdditionalAllocationData';
import {
  AdditionalAllocationDataFromJSON,
  AdditionalAllocationDataFromJSONTyped,
  AdditionalAllocationDataToJSON,
  AdditionalAllocationDataToJSONTyped
} from './AdditionalAllocationData';

/**
 * @export
 * @interface DatasourceAllocationMultipleBodyResourcesInner
 */
export interface DatasourceAllocationMultipleBodyResourcesInner {
  /**
   * @memberof DatasourceAllocationMultipleBodyResourcesInner
   * @type {number}
   */
  resourceId: number;
  /**
   * @memberof DatasourceAllocationMultipleBodyResourcesInner
   * @type {string}
   */
  type?: string | null;
  /**
   * @memberof DatasourceAllocationMultipleBodyResourcesInner
   * @type {string}
   */
  comment?: string | null;
  /**
   * @memberof DatasourceAllocationMultipleBodyResourcesInner
   * @type {Date}
   */
  start: Date;
  /**
   * @memberof DatasourceAllocationMultipleBodyResourcesInner
   * @type {Date}
   */
  end: Date;
  /**
   * @memberof DatasourceAllocationMultipleBodyResourcesInner
   * @type {number}
   */
  parentId?: number | null;
  /**
   * @memberof DatasourceAllocationMultipleBodyResourcesInner
   * @type {AdditionalAllocationData[]}
   */
  fields?: Array<AdditionalAllocationData> | null;
}

/**
 * Check if a given object implements the
 * DatasourceAllocationMultipleBodyResourcesInner interface.
 */
export function instanceOfDatasourceAllocationMultipleBodyResourcesInner(
  value: object
): value is DatasourceAllocationMultipleBodyResourcesInner {
  if (!('resourceId' in value) || value['resourceId'] === undefined)
    return false;
  if (!('start' in value) || value['start'] === undefined) return false;
  if (!('end' in value) || value['end'] === undefined) return false;
  return true;
}

export function DatasourceAllocationMultipleBodyResourcesInnerFromJSON(
  json: any
): DatasourceAllocationMultipleBodyResourcesInner {
  return DatasourceAllocationMultipleBodyResourcesInnerFromJSONTyped(
    json,
    false
  );
}

export function DatasourceAllocationMultipleBodyResourcesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DatasourceAllocationMultipleBodyResourcesInner {
  if (json == null) {
    return json;
  }
  return {
    resourceId: json['resource_id'],
    type: json['type'] == null ? undefined : json['type'],
    comment: json['comment'] == null ? undefined : json['comment'],
    start: new Date(json['start']),
    end: new Date(json['end']),
    parentId: json['parent_id'] == null ? undefined : json['parent_id'],
    fields:
      json['fields'] == null
        ? undefined
        : (json['fields'] as Array<any>).map(AdditionalAllocationDataFromJSON)
  };
}

export function DatasourceAllocationMultipleBodyResourcesInnerToJSON(
  json: any
): DatasourceAllocationMultipleBodyResourcesInner {
  return DatasourceAllocationMultipleBodyResourcesInnerToJSONTyped(json, false);
}

export function DatasourceAllocationMultipleBodyResourcesInnerToJSONTyped(
  value?: DatasourceAllocationMultipleBodyResourcesInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    resource_id: value['resourceId'],
    type: value['type'],
    comment: value['comment'],
    start: value['start'].toISOString(),
    end: value['end'].toISOString(),
    parent_id: value['parentId'],
    fields:
      value['fields'] == null
        ? undefined
        : (value['fields'] as Array<any>).map(AdditionalAllocationDataToJSON)
  };
}
