/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface DatasourceExtraDataFieldsInnerOptionsInner
 */
export interface DatasourceExtraDataFieldsInnerOptionsInner {
  /**
   * @memberof DatasourceExtraDataFieldsInnerOptionsInner
   * @type {string}
   */
  value?: string;
  /**
   * @memberof DatasourceExtraDataFieldsInnerOptionsInner
   * @type {string}
   */
  label?: string;
}

/**
 * Check if a given object implements the
 * DatasourceExtraDataFieldsInnerOptionsInner interface.
 */
export function instanceOfDatasourceExtraDataFieldsInnerOptionsInner(
  value: object
): value is DatasourceExtraDataFieldsInnerOptionsInner {
  return true;
}

export function DatasourceExtraDataFieldsInnerOptionsInnerFromJSON(
  json: any
): DatasourceExtraDataFieldsInnerOptionsInner {
  return DatasourceExtraDataFieldsInnerOptionsInnerFromJSONTyped(json, false);
}

export function DatasourceExtraDataFieldsInnerOptionsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DatasourceExtraDataFieldsInnerOptionsInner {
  if (json == null) {
    return json;
  }
  return {
    value: json['value'] == null ? undefined : json['value'],
    label: json['label'] == null ? undefined : json['label']
  };
}

export function DatasourceExtraDataFieldsInnerOptionsInnerToJSON(
  json: any
): DatasourceExtraDataFieldsInnerOptionsInner {
  return DatasourceExtraDataFieldsInnerOptionsInnerToJSONTyped(json, false);
}

export function DatasourceExtraDataFieldsInnerOptionsInnerToJSONTyped(
  value?: DatasourceExtraDataFieldsInnerOptionsInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    value: value['value'],
    label: value['label']
  };
}
