/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { DatasourceEntryData } from './DatasourceEntryData';
import {
  DatasourceEntryDataFromJSON,
  DatasourceEntryDataFromJSONTyped,
  DatasourceEntryDataToJSON,
  DatasourceEntryDataToJSONTyped
} from './DatasourceEntryData';

/**
 * @export
 * @interface DatasourceEntry
 */
export interface DatasourceEntry {
  /**
   * @memberof DatasourceEntry
   * @type {number}
   */
  id?: number;
  /**
   * @memberof DatasourceEntry
   * @type {number}
   */
  datasourceId?: number;
  /**
   * @memberof DatasourceEntry
   * @type {DatasourceEntryData}
   */
  data?: DatasourceEntryData;
  /**
   * Due to past config, no timestamp was stored for historic records.
   *
   * @memberof DatasourceEntry
   * @type {Date}
   */
  createdAt?: Date | null;
  /**
   * Due to past config, no timestamp was stored for historic records.
   *
   * @memberof DatasourceEntry
   * @type {Date}
   */
  updatedAt?: Date | null;
}

/** Check if a given object implements the DatasourceEntry interface. */
export function instanceOfDatasourceEntry(
  value: object
): value is DatasourceEntry {
  return true;
}

export function DatasourceEntryFromJSON(json: any): DatasourceEntry {
  return DatasourceEntryFromJSONTyped(json, false);
}

export function DatasourceEntryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DatasourceEntry {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    datasourceId:
      json['datasource_id'] == null ? undefined : json['datasource_id'],
    data:
      json['data'] == null
        ? undefined
        : DatasourceEntryDataFromJSON(json['data']),
    createdAt:
      json['created_at'] == null ? undefined : new Date(json['created_at']),
    updatedAt:
      json['updated_at'] == null ? undefined : new Date(json['updated_at'])
  };
}

export function DatasourceEntryToJSON(json: any): DatasourceEntry {
  return DatasourceEntryToJSONTyped(json, false);
}

export function DatasourceEntryToJSONTyped(
  value?: DatasourceEntry | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    datasource_id: value['datasourceId'],
    data: DatasourceEntryDataToJSON(value['data']),
    created_at:
      value['createdAt'] == null
        ? undefined
        : (value['createdAt'] as any).toISOString(),
    updated_at:
      value['updatedAt'] == null
        ? undefined
        : (value['updatedAt'] as any).toISOString()
  };
}
