/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface DatasourceResourceGroupsInner
 */
export interface DatasourceResourceGroupsInner {
  /**
   * @memberof DatasourceResourceGroupsInner
   * @type {string}
   */
  name?: string;
  /**
   * @memberof DatasourceResourceGroupsInner
   * @type {string}
   */
  label?: string;
  /**
   * @memberof DatasourceResourceGroupsInner
   * @type {string}
   */
  slug?: string;
}

/**
 * Check if a given object implements the DatasourceResourceGroupsInner
 * interface.
 */
export function instanceOfDatasourceResourceGroupsInner(
  value: object
): value is DatasourceResourceGroupsInner {
  return true;
}

export function DatasourceResourceGroupsInnerFromJSON(
  json: any
): DatasourceResourceGroupsInner {
  return DatasourceResourceGroupsInnerFromJSONTyped(json, false);
}

export function DatasourceResourceGroupsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DatasourceResourceGroupsInner {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    label: json['label'] == null ? undefined : json['label'],
    slug: json['slug'] == null ? undefined : json['slug']
  };
}

export function DatasourceResourceGroupsInnerToJSON(
  json: any
): DatasourceResourceGroupsInner {
  return DatasourceResourceGroupsInnerToJSONTyped(json, false);
}

export function DatasourceResourceGroupsInnerToJSONTyped(
  value?: DatasourceResourceGroupsInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    label: value['label'],
    slug: value['slug']
  };
}
