/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface DatasourceEntryData
 */
export interface DatasourceEntryData {
  /**
   * @memberof DatasourceEntryData
   * @type {string}
   */
  name?: string;
  /**
   * @memberof DatasourceEntryData
   * @type {string}
   */
  example2?: string;
}

/** Check if a given object implements the DatasourceEntryData interface. */
export function instanceOfDatasourceEntryData(
  value: object
): value is DatasourceEntryData {
  return true;
}

export function DatasourceEntryDataFromJSON(json: any): DatasourceEntryData {
  return DatasourceEntryDataFromJSONTyped(json, false);
}

export function DatasourceEntryDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DatasourceEntryData {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    example2: json['example2'] == null ? undefined : json['example2']
  };
}

export function DatasourceEntryDataToJSON(json: any): DatasourceEntryData {
  return DatasourceEntryDataToJSONTyped(json, false);
}

export function DatasourceEntryDataToJSONTyped(
  value?: DatasourceEntryData | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    example2: value['example2']
  };
}
