/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { DatasourceAllocationMultipleUpdateBodyAllocationsInner } from './DatasourceAllocationMultipleUpdateBodyAllocationsInner';
import {
  DatasourceAllocationMultipleUpdateBodyAllocationsInnerFromJSON,
  DatasourceAllocationMultipleUpdateBodyAllocationsInnerFromJSONTyped,
  DatasourceAllocationMultipleUpdateBodyAllocationsInnerToJSON,
  DatasourceAllocationMultipleUpdateBodyAllocationsInnerToJSONTyped
} from './DatasourceAllocationMultipleUpdateBodyAllocationsInner';

/**
 * @export
 * @interface DatasourceAllocationMultipleUpdateBody
 */
export interface DatasourceAllocationMultipleUpdateBody {
  /**
   * @memberof DatasourceAllocationMultipleUpdateBody
   * @type {DatasourceAllocationMultipleUpdateBodyAllocationsInner[]}
   */
  allocations: Array<DatasourceAllocationMultipleUpdateBodyAllocationsInner>;
}

/**
 * Check if a given object implements the DatasourceAllocationMultipleUpdateBody
 * interface.
 */
export function instanceOfDatasourceAllocationMultipleUpdateBody(
  value: object
): value is DatasourceAllocationMultipleUpdateBody {
  if (!('allocations' in value) || value['allocations'] === undefined)
    return false;
  return true;
}

export function DatasourceAllocationMultipleUpdateBodyFromJSON(
  json: any
): DatasourceAllocationMultipleUpdateBody {
  return DatasourceAllocationMultipleUpdateBodyFromJSONTyped(json, false);
}

export function DatasourceAllocationMultipleUpdateBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DatasourceAllocationMultipleUpdateBody {
  if (json == null) {
    return json;
  }
  return {
    allocations: (json['allocations'] as Array<any>).map(
      DatasourceAllocationMultipleUpdateBodyAllocationsInnerFromJSON
    )
  };
}

export function DatasourceAllocationMultipleUpdateBodyToJSON(
  json: any
): DatasourceAllocationMultipleUpdateBody {
  return DatasourceAllocationMultipleUpdateBodyToJSONTyped(json, false);
}

export function DatasourceAllocationMultipleUpdateBodyToJSONTyped(
  value?: DatasourceAllocationMultipleUpdateBody | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    allocations: (value['allocations'] as Array<any>).map(
      DatasourceAllocationMultipleUpdateBodyAllocationsInnerToJSON
    )
  };
}
