/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface DatasourceResource
 */
export interface DatasourceResource {
  /**
   * @memberof DatasourceResource
   * @type {number}
   */
  id?: number;
  /**
   * Use this field to display to the user
   *
   * @memberof DatasourceResource
   * @type {string}
   */
  label?: string;
  /**
   * @memberof DatasourceResource
   * @type {string}
   */
  name?: string;
  /**
   * @memberof DatasourceResource
   * @type {Date}
   */
  createdAt?: Date;
  /**
   * @memberof DatasourceResource
   * @type {Date}
   */
  updatedAt?: Date;
}

/** Check if a given object implements the DatasourceResource interface. */
export function instanceOfDatasourceResource(
  value: object
): value is DatasourceResource {
  return true;
}

export function DatasourceResourceFromJSON(json: any): DatasourceResource {
  return DatasourceResourceFromJSONTyped(json, false);
}

export function DatasourceResourceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DatasourceResource {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    label: json['label'] == null ? undefined : json['label'],
    name: json['name'] == null ? undefined : json['name'],
    createdAt:
      json['created_at'] == null ? undefined : new Date(json['created_at']),
    updatedAt:
      json['updated_at'] == null ? undefined : new Date(json['updated_at'])
  };
}

export function DatasourceResourceToJSON(json: any): DatasourceResource {
  return DatasourceResourceToJSONTyped(json, false);
}

export function DatasourceResourceToJSONTyped(
  value?: DatasourceResource | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    label: value['label'],
    name: value['name'],
    created_at:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updated_at:
      value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString()
  };
}
