/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { AllocationTypesAllocationTypesInner } from './AllocationTypesAllocationTypesInner';
import {
  AllocationTypesAllocationTypesInnerFromJSON,
  AllocationTypesAllocationTypesInnerFromJSONTyped,
  AllocationTypesAllocationTypesInnerToJSON,
  AllocationTypesAllocationTypesInnerToJSONTyped
} from './AllocationTypesAllocationTypesInner';

/**
 * @export
 * @interface DatasourceProject
 */
export interface DatasourceProject {
  /**
   * @memberof DatasourceProject
   * @type {number}
   */
  id?: number;
  /**
   * @memberof DatasourceProject
   * @type {number}
   */
  datasourceId?: number | null;
  /**
   * Use this field to display to the user
   *
   * @memberof DatasourceProject
   * @type {string}
   */
  label?: string;
  /**
   * @memberof DatasourceProject
   * @type {string}
   */
  name?: string;
  /**
   * @memberof DatasourceProject
   * @type {Date}
   */
  start?: Date;
  /**
   * @memberof DatasourceProject
   * @type {Date}
   */
  end?: Date;
  /**
   * @memberof DatasourceProject
   * @type {string}
   */
  color?: string;
  /**
   * @memberof DatasourceProject
   * @type {object}
   */
  extraData?: object | null;
  /**
   * @memberof DatasourceProject
   * @type {AllocationTypesAllocationTypesInner[]}
   */
  allocationTypes?: Array<AllocationTypesAllocationTypesInner> | null;
}

/** Check if a given object implements the DatasourceProject interface. */
export function instanceOfDatasourceProject(
  value: object
): value is DatasourceProject {
  return true;
}

export function DatasourceProjectFromJSON(json: any): DatasourceProject {
  return DatasourceProjectFromJSONTyped(json, false);
}

export function DatasourceProjectFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DatasourceProject {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    datasourceId:
      json['datasource_id'] == null ? undefined : json['datasource_id'],
    label: json['label'] == null ? undefined : json['label'],
    name: json['name'] == null ? undefined : json['name'],
    start: json['start'] == null ? undefined : new Date(json['start']),
    end: json['end'] == null ? undefined : new Date(json['end']),
    color: json['color'] == null ? undefined : json['color'],
    extraData: json['extra_data'] == null ? undefined : json['extra_data'],
    allocationTypes:
      json['allocation_types'] == null
        ? undefined
        : (json['allocation_types'] as Array<any>).map(
            AllocationTypesAllocationTypesInnerFromJSON
          )
  };
}

export function DatasourceProjectToJSON(json: any): DatasourceProject {
  return DatasourceProjectToJSONTyped(json, false);
}

export function DatasourceProjectToJSONTyped(
  value?: DatasourceProject | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    datasource_id: value['datasourceId'],
    label: value['label'],
    name: value['name'],
    start: value['start'] == null ? undefined : value['start'].toISOString(),
    end: value['end'] == null ? undefined : value['end'].toISOString(),
    color: value['color'],
    extra_data: value['extraData'],
    allocation_types:
      value['allocationTypes'] == null
        ? undefined
        : (value['allocationTypes'] as Array<any>).map(
            AllocationTypesAllocationTypesInnerToJSON
          )
  };
}
