/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityDatumProjectResourceAllocationsGroupedInnerAllocationsInner } from './EntityDatumProjectResourceAllocationsGroupedInnerAllocationsInner';
import {
  EntityDatumProjectResourceAllocationsGroupedInnerAllocationsInnerFromJSON,
  EntityDatumProjectResourceAllocationsGroupedInnerAllocationsInnerFromJSONTyped,
  EntityDatumProjectResourceAllocationsGroupedInnerAllocationsInnerToJSON,
  EntityDatumProjectResourceAllocationsGroupedInnerAllocationsInnerToJSONTyped
} from './EntityDatumProjectResourceAllocationsGroupedInnerAllocationsInner';

/**
 * @export
 * @interface EntityDatumProjectResourceAllocationsGroupedInner
 */
export interface EntityDatumProjectResourceAllocationsGroupedInner {
  /**
   * @memberof EntityDatumProjectResourceAllocationsGroupedInner
   * @type {number}
   */
  id?: number;
  /**
   * @memberof EntityDatumProjectResourceAllocationsGroupedInner
   * @type {string}
   */
  label?: string;
  /**
   * @memberof EntityDatumProjectResourceAllocationsGroupedInner
   * @type {EntityDatumProjectResourceAllocationsGroupedInnerAllocationsInner[]}
   */
  allocations?: Array<EntityDatumProjectResourceAllocationsGroupedInnerAllocationsInner>;
  /**
   * @memberof EntityDatumProjectResourceAllocationsGroupedInner
   * @type {Date}
   */
  createdAt?: Date;
  /**
   * @memberof EntityDatumProjectResourceAllocationsGroupedInner
   * @type {Date}
   */
  updatedAt?: Date;
}

/**
 * Check if a given object implements the
 * EntityDatumProjectResourceAllocationsGroupedInner interface.
 */
export function instanceOfEntityDatumProjectResourceAllocationsGroupedInner(
  value: object
): value is EntityDatumProjectResourceAllocationsGroupedInner {
  return true;
}

export function EntityDatumProjectResourceAllocationsGroupedInnerFromJSON(
  json: any
): EntityDatumProjectResourceAllocationsGroupedInner {
  return EntityDatumProjectResourceAllocationsGroupedInnerFromJSONTyped(
    json,
    false
  );
}

export function EntityDatumProjectResourceAllocationsGroupedInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityDatumProjectResourceAllocationsGroupedInner {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    label: json['label'] == null ? undefined : json['label'],
    allocations:
      json['allocations'] == null
        ? undefined
        : (json['allocations'] as Array<any>).map(
            EntityDatumProjectResourceAllocationsGroupedInnerAllocationsInnerFromJSON
          ),
    createdAt:
      json['created_at'] == null ? undefined : new Date(json['created_at']),
    updatedAt:
      json['updated_at'] == null ? undefined : new Date(json['updated_at'])
  };
}

export function EntityDatumProjectResourceAllocationsGroupedInnerToJSON(
  json: any
): EntityDatumProjectResourceAllocationsGroupedInner {
  return EntityDatumProjectResourceAllocationsGroupedInnerToJSONTyped(
    json,
    false
  );
}

export function EntityDatumProjectResourceAllocationsGroupedInnerToJSONTyped(
  value?: EntityDatumProjectResourceAllocationsGroupedInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    label: value['label'],
    allocations:
      value['allocations'] == null
        ? undefined
        : (value['allocations'] as Array<any>).map(
            EntityDatumProjectResourceAllocationsGroupedInnerAllocationsInnerToJSON
          ),
    created_at:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updated_at:
      value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString()
  };
}
