/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityDatumProjectResourceAllocationsGroupedInner } from './EntityDatumProjectResourceAllocationsGroupedInner';
import {
  EntityDatumProjectResourceAllocationsGroupedInnerFromJSON,
  EntityDatumProjectResourceAllocationsGroupedInnerFromJSONTyped,
  EntityDatumProjectResourceAllocationsGroupedInnerToJSON,
  EntityDatumProjectResourceAllocationsGroupedInnerToJSONTyped
} from './EntityDatumProjectResourceAllocationsGroupedInner';

/**
 * @export
 * @interface EntityDatumProjectResource
 */
export interface EntityDatumProjectResource {
  /**
   * @memberof EntityDatumProjectResource
   * @type {EntityDatumProjectResourceAllocationsGroupedInner[]}
   */
  allocationsGrouped?: Array<EntityDatumProjectResourceAllocationsGroupedInner>;
}

/** Check if a given object implements the EntityDatumProjectResource interface. */
export function instanceOfEntityDatumProjectResource(
  value: object
): value is EntityDatumProjectResource {
  return true;
}

export function EntityDatumProjectResourceFromJSON(
  json: any
): EntityDatumProjectResource {
  return EntityDatumProjectResourceFromJSONTyped(json, false);
}

export function EntityDatumProjectResourceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityDatumProjectResource {
  if (json == null) {
    return json;
  }
  return {
    allocationsGrouped:
      json['allocations_grouped'] == null
        ? undefined
        : (json['allocations_grouped'] as Array<any>).map(
            EntityDatumProjectResourceAllocationsGroupedInnerFromJSON
          )
  };
}

export function EntityDatumProjectResourceToJSON(
  json: any
): EntityDatumProjectResource {
  return EntityDatumProjectResourceToJSONTyped(json, false);
}

export function EntityDatumProjectResourceToJSONTyped(
  value?: EntityDatumProjectResource | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    allocations_grouped:
      value['allocationsGrouped'] == null
        ? undefined
        : (value['allocationsGrouped'] as Array<any>).map(
            EntityDatumProjectResourceAllocationsGroupedInnerToJSON
          )
  };
}
