/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface MessageResourceBody
 */
export interface MessageResourceBody {
  /**
   * @memberof MessageResourceBody
   * @type {string}
   */
  text: string;
}

/** Check if a given object implements the MessageResourceBody interface. */
export function instanceOfMessageResourceBody(
  value: object
): value is MessageResourceBody {
  if (!('text' in value) || value['text'] === undefined) return false;
  return true;
}

export function MessageResourceBodyFromJSON(json: any): MessageResourceBody {
  return MessageResourceBodyFromJSONTyped(json, false);
}

export function MessageResourceBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MessageResourceBody {
  if (json == null) {
    return json;
  }
  return {
    text: json['text']
  };
}

export function MessageResourceBodyToJSON(json: any): MessageResourceBody {
  return MessageResourceBodyToJSONTyped(json, false);
}

export function MessageResourceBodyToJSONTyped(
  value?: MessageResourceBody | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    text: value['text']
  };
}
