/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface PaginationMetaLinksInner
 */
export interface PaginationMetaLinksInner {
  /**
   * @memberof PaginationMetaLinksInner
   * @type {string}
   */
  url?: string;
  /**
   * @memberof PaginationMetaLinksInner
   * @type {string}
   */
  label?: string;
  /**
   * @memberof PaginationMetaLinksInner
   * @type {boolean}
   */
  active?: boolean;
}

/** Check if a given object implements the PaginationMetaLinksInner interface. */
export function instanceOfPaginationMetaLinksInner(
  value: object
): value is PaginationMetaLinksInner {
  return true;
}

export function PaginationMetaLinksInnerFromJSON(
  json: any
): PaginationMetaLinksInner {
  return PaginationMetaLinksInnerFromJSONTyped(json, false);
}

export function PaginationMetaLinksInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginationMetaLinksInner {
  if (json == null) {
    return json;
  }
  return {
    url: json['url'] == null ? undefined : json['url'],
    label: json['label'] == null ? undefined : json['label'],
    active: json['active'] == null ? undefined : json['active']
  };
}

export function PaginationMetaLinksInnerToJSON(
  json: any
): PaginationMetaLinksInner {
  return PaginationMetaLinksInnerToJSONTyped(json, false);
}

export function PaginationMetaLinksInnerToJSONTyped(
  value?: PaginationMetaLinksInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    url: value['url'],
    label: value['label'],
    active: value['active']
  };
}
