/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface PaginationLinks
 */
export interface PaginationLinks {
  /**
   * @memberof PaginationLinks
   * @type {string}
   */
  first?: string;
  /**
   * @memberof PaginationLinks
   * @type {string}
   */
  last?: string;
  /**
   * @memberof PaginationLinks
   * @type {string}
   */
  prev?: string;
  /**
   * @memberof PaginationLinks
   * @type {string}
   */
  next?: string;
}

/** Check if a given object implements the PaginationLinks interface. */
export function instanceOfPaginationLinks(
  value: object
): value is PaginationLinks {
  return true;
}

export function PaginationLinksFromJSON(json: any): PaginationLinks {
  return PaginationLinksFromJSONTyped(json, false);
}

export function PaginationLinksFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginationLinks {
  if (json == null) {
    return json;
  }
  return {
    first: json['first'] == null ? undefined : json['first'],
    last: json['last'] == null ? undefined : json['last'],
    prev: json['prev'] == null ? undefined : json['prev'],
    next: json['next'] == null ? undefined : json['next']
  };
}

export function PaginationLinksToJSON(json: any): PaginationLinks {
  return PaginationLinksToJSONTyped(json, false);
}

export function PaginationLinksToJSONTyped(
  value?: PaginationLinks | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    first: value['first'],
    last: value['last'],
    prev: value['prev'],
    next: value['next']
  };
}
