/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMetaLinksInner } from './PaginationMetaLinksInner';
import {
  PaginationMetaLinksInnerFromJSON,
  PaginationMetaLinksInnerFromJSONTyped,
  PaginationMetaLinksInnerToJSON,
  PaginationMetaLinksInnerToJSONTyped
} from './PaginationMetaLinksInner';

/**
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
  /**
   * @memberof PaginationMeta
   * @type {number}
   */
  currentPage?: number;
  /**
   * @memberof PaginationMeta
   * @type {number}
   */
  lastPage?: number;
  /**
   * @memberof PaginationMeta
   * @type {PaginationMetaLinksInner[]}
   */
  links?: Array<PaginationMetaLinksInner>;
  /**
   * @memberof PaginationMeta
   * @type {string}
   */
  path?: string;
  /**
   * @memberof PaginationMeta
   * @type {number}
   */
  perPage?: number;
  /**
   * @memberof PaginationMeta
   * @type {number}
   */
  from?: number;
  /**
   * @memberof PaginationMeta
   * @type {number}
   */
  to?: number;
  /**
   * @memberof PaginationMeta
   * @type {number}
   */
  total?: number;
}

/** Check if a given object implements the PaginationMeta interface. */
export function instanceOfPaginationMeta(
  value: object
): value is PaginationMeta {
  return true;
}

export function PaginationMetaFromJSON(json: any): PaginationMeta {
  return PaginationMetaFromJSONTyped(json, false);
}

export function PaginationMetaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginationMeta {
  if (json == null) {
    return json;
  }
  return {
    currentPage:
      json['current_page'] == null ? undefined : json['current_page'],
    lastPage: json['last_page'] == null ? undefined : json['last_page'],
    links:
      json['links'] == null
        ? undefined
        : (json['links'] as Array<any>).map(PaginationMetaLinksInnerFromJSON),
    path: json['path'] == null ? undefined : json['path'],
    perPage: json['per_page'] == null ? undefined : json['per_page'],
    from: json['from'] == null ? undefined : json['from'],
    to: json['to'] == null ? undefined : json['to'],
    total: json['total'] == null ? undefined : json['total']
  };
}

export function PaginationMetaToJSON(json: any): PaginationMeta {
  return PaginationMetaToJSONTyped(json, false);
}

export function PaginationMetaToJSONTyped(
  value?: PaginationMeta | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    current_page: value['currentPage'],
    last_page: value['lastPage'],
    links:
      value['links'] == null
        ? undefined
        : (value['links'] as Array<any>).map(PaginationMetaLinksInnerToJSON),
    path: value['path'],
    per_page: value['perPage'],
    from: value['from'],
    to: value['to'],
    total: value['total']
  };
}
