/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface PhaseUpdateBody
 */
export interface PhaseUpdateBody {
  /**
   * @memberof PhaseUpdateBody
   * @type {Date}
   */
  start: Date;
  /**
   * @memberof PhaseUpdateBody
   * @type {Date}
   */
  end: Date;
  /**
   * @memberof PhaseUpdateBody
   * @type {boolean}
   */
  isStaged?: boolean;
}

/** Check if a given object implements the PhaseUpdateBody interface. */
export function instanceOfPhaseUpdateBody(
  value: object
): value is PhaseUpdateBody {
  if (!('start' in value) || value['start'] === undefined) return false;
  if (!('end' in value) || value['end'] === undefined) return false;
  return true;
}

export function PhaseUpdateBodyFromJSON(json: any): PhaseUpdateBody {
  return PhaseUpdateBodyFromJSONTyped(json, false);
}

export function PhaseUpdateBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PhaseUpdateBody {
  if (json == null) {
    return json;
  }
  return {
    start: new Date(json['start']),
    end: new Date(json['end']),
    isStaged: json['is_staged'] == null ? undefined : json['is_staged']
  };
}

export function PhaseUpdateBodyToJSON(json: any): PhaseUpdateBody {
  return PhaseUpdateBodyToJSONTyped(json, false);
}

export function PhaseUpdateBodyToJSONTyped(
  value?: PhaseUpdateBody | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    start: value['start'].toISOString(),
    end: value['end'].toISOString(),
    is_staged: value['isStaged']
  };
}
