/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface Timestamps
 */
export interface Timestamps {
  /**
   * @memberof Timestamps
   * @type {Date}
   */
  createdAt?: Date;
  /**
   * @memberof Timestamps
   * @type {Date}
   */
  updatedAt?: Date;
}

/** Check if a given object implements the Timestamps interface. */
export function instanceOfTimestamps(value: object): value is Timestamps {
  return true;
}

export function TimestampsFromJSON(json: any): Timestamps {
  return TimestampsFromJSONTyped(json, false);
}

export function TimestampsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Timestamps {
  if (json == null) {
    return json;
  }
  return {
    createdAt:
      json['created_at'] == null ? undefined : new Date(json['created_at']),
    updatedAt:
      json['updated_at'] == null ? undefined : new Date(json['updated_at'])
  };
}

export function TimestampsToJSON(json: any): Timestamps {
  return TimestampsToJSONTyped(json, false);
}

export function TimestampsToJSONTyped(
  value?: Timestamps | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    created_at:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updated_at:
      value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString()
  };
}
