/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface UserResource
 */
export interface UserResource {
  /**
   * @memberof UserResource
   * @type {number}
   */
  id?: number;
  /**
   * @memberof UserResource
   * @type {string}
   */
  fullname?: string;
  /**
   * @memberof UserResource
   * @type {string}
   */
  email?: string;
  /**
   * @memberof UserResource
   * @type {Date}
   */
  createdAt?: Date;
  /**
   * @memberof UserResource
   * @type {Date}
   */
  updatedAt?: Date;
}

/** Check if a given object implements the UserResource interface. */
export function instanceOfUserResource(value: object): value is UserResource {
  return true;
}

export function UserResourceFromJSON(json: any): UserResource {
  return UserResourceFromJSONTyped(json, false);
}

export function UserResourceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserResource {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    fullname: json['fullname'] == null ? undefined : json['fullname'],
    email: json['email'] == null ? undefined : json['email'],
    createdAt:
      json['created_at'] == null ? undefined : new Date(json['created_at']),
    updatedAt:
      json['updated_at'] == null ? undefined : new Date(json['updated_at'])
  };
}

export function UserResourceToJSON(json: any): UserResource {
  return UserResourceToJSONTyped(json, false);
}

export function UserResourceToJSONTyped(
  value?: UserResource | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    fullname: value['fullname'],
    email: value['email'],
    created_at:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updated_at:
      value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString()
  };
}
