/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { AnnouncementResource } from './AnnouncementResource';
import {
  AnnouncementResourceFromJSON,
  AnnouncementResourceFromJSONTyped,
  AnnouncementResourceToJSON,
  AnnouncementResourceToJSONTyped
} from './AnnouncementResource';

/**
 * @export
 * @interface V2AnnouncementAnnouncementIdGet200Response
 */
export interface V2AnnouncementAnnouncementIdGet200Response {
  /**
   * @memberof V2AnnouncementAnnouncementIdGet200Response
   * @type {AnnouncementResource}
   */
  data?: AnnouncementResource;
}

/**
 * Check if a given object implements the
 * V2AnnouncementAnnouncementIdGet200Response interface.
 */
export function instanceOfV2AnnouncementAnnouncementIdGet200Response(
  value: object
): value is V2AnnouncementAnnouncementIdGet200Response {
  return true;
}

export function V2AnnouncementAnnouncementIdGet200ResponseFromJSON(
  json: any
): V2AnnouncementAnnouncementIdGet200Response {
  return V2AnnouncementAnnouncementIdGet200ResponseFromJSONTyped(json, false);
}

export function V2AnnouncementAnnouncementIdGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2AnnouncementAnnouncementIdGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : AnnouncementResourceFromJSON(json['data'])
  };
}

export function V2AnnouncementAnnouncementIdGet200ResponseToJSON(
  json: any
): V2AnnouncementAnnouncementIdGet200Response {
  return V2AnnouncementAnnouncementIdGet200ResponseToJSONTyped(json, false);
}

export function V2AnnouncementAnnouncementIdGet200ResponseToJSONTyped(
  value?: V2AnnouncementAnnouncementIdGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: AnnouncementResourceToJSON(value['data'])
  };
}
