/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { AnnouncementResource } from './AnnouncementResource';
import {
  AnnouncementResourceFromJSON,
  AnnouncementResourceFromJSONTyped,
  AnnouncementResourceToJSON,
  AnnouncementResourceToJSONTyped
} from './AnnouncementResource';

/**
 * @export
 * @interface V2AnnouncementsGet200Response
 */
export interface V2AnnouncementsGet200Response {
  /**
   * @memberof V2AnnouncementsGet200Response
   * @type {AnnouncementResource[]}
   */
  data?: Array<AnnouncementResource>;
}

/**
 * Check if a given object implements the V2AnnouncementsGet200Response
 * interface.
 */
export function instanceOfV2AnnouncementsGet200Response(
  value: object
): value is V2AnnouncementsGet200Response {
  return true;
}

export function V2AnnouncementsGet200ResponseFromJSON(
  json: any
): V2AnnouncementsGet200Response {
  return V2AnnouncementsGet200ResponseFromJSONTyped(json, false);
}

export function V2AnnouncementsGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2AnnouncementsGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(AnnouncementResourceFromJSON)
  };
}

export function V2AnnouncementsGet200ResponseToJSON(
  json: any
): V2AnnouncementsGet200Response {
  return V2AnnouncementsGet200ResponseToJSONTyped(json, false);
}

export function V2AnnouncementsGet200ResponseToJSONTyped(
  value?: V2AnnouncementsGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(AnnouncementResourceToJSON)
  };
}
