/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface V2ConfigurationGet200ResponseDefaultTimePeriod
 */
export interface V2ConfigurationGet200ResponseDefaultTimePeriod {
  /**
   * @memberof V2ConfigurationGet200ResponseDefaultTimePeriod
   * @type {Date}
   */
  start?: Date;
  /**
   * @memberof V2ConfigurationGet200ResponseDefaultTimePeriod
   * @type {Date}
   */
  end?: Date;
  /**
   * @memberof V2ConfigurationGet200ResponseDefaultTimePeriod
   * @type {Date}
   */
  interval?: Date;
}

/**
 * Check if a given object implements the
 * V2ConfigurationGet200ResponseDefaultTimePeriod interface.
 */
export function instanceOfV2ConfigurationGet200ResponseDefaultTimePeriod(
  value: object
): value is V2ConfigurationGet200ResponseDefaultTimePeriod {
  return true;
}

export function V2ConfigurationGet200ResponseDefaultTimePeriodFromJSON(
  json: any
): V2ConfigurationGet200ResponseDefaultTimePeriod {
  return V2ConfigurationGet200ResponseDefaultTimePeriodFromJSONTyped(
    json,
    false
  );
}

export function V2ConfigurationGet200ResponseDefaultTimePeriodFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2ConfigurationGet200ResponseDefaultTimePeriod {
  if (json == null) {
    return json;
  }
  return {
    start: json['start'] == null ? undefined : new Date(json['start']),
    end: json['end'] == null ? undefined : new Date(json['end']),
    interval: json['interval'] == null ? undefined : new Date(json['interval'])
  };
}

export function V2ConfigurationGet200ResponseDefaultTimePeriodToJSON(
  json: any
): V2ConfigurationGet200ResponseDefaultTimePeriod {
  return V2ConfigurationGet200ResponseDefaultTimePeriodToJSONTyped(json, false);
}

export function V2ConfigurationGet200ResponseDefaultTimePeriodToJSONTyped(
  value?: V2ConfigurationGet200ResponseDefaultTimePeriod | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    start: value['start'] == null ? undefined : value['start'].toISOString(),
    end: value['end'] == null ? undefined : value['end'].toISOString(),
    interval:
      value['interval'] == null ? undefined : value['interval'].toISOString()
  };
}
