/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { V2ConfigurationGet200ResponseCan } from './V2ConfigurationGet200ResponseCan';
import {
  V2ConfigurationGet200ResponseCanFromJSON,
  V2ConfigurationGet200ResponseCanFromJSONTyped,
  V2ConfigurationGet200ResponseCanToJSON,
  V2ConfigurationGet200ResponseCanToJSONTyped
} from './V2ConfigurationGet200ResponseCan';
import type { V2ConfigurationGet200ResponseDefaultTimePeriod } from './V2ConfigurationGet200ResponseDefaultTimePeriod';
import {
  V2ConfigurationGet200ResponseDefaultTimePeriodFromJSON,
  V2ConfigurationGet200ResponseDefaultTimePeriodFromJSONTyped,
  V2ConfigurationGet200ResponseDefaultTimePeriodToJSON,
  V2ConfigurationGet200ResponseDefaultTimePeriodToJSONTyped
} from './V2ConfigurationGet200ResponseDefaultTimePeriod';
import type { V2ConfigurationGet200ResponseFilters } from './V2ConfigurationGet200ResponseFilters';
import {
  V2ConfigurationGet200ResponseFiltersFromJSON,
  V2ConfigurationGet200ResponseFiltersFromJSONTyped,
  V2ConfigurationGet200ResponseFiltersToJSON,
  V2ConfigurationGet200ResponseFiltersToJSONTyped
} from './V2ConfigurationGet200ResponseFilters';

/**
 * @export
 * @interface V2ConfigurationGet200Response
 */
export interface V2ConfigurationGet200Response {
  /**
   * @memberof V2ConfigurationGet200Response
   * @type {object}
   */
  _configuration?: object;
  /**
   * @memberof V2ConfigurationGet200Response
   * @type {V2ConfigurationGet200ResponseCan}
   */
  can?: V2ConfigurationGet200ResponseCan;
  /**
   * @memberof V2ConfigurationGet200Response
   * @type {V2ConfigurationGet200ResponseDefaultTimePeriod}
   */
  defaultTimePeriod?: V2ConfigurationGet200ResponseDefaultTimePeriod;
  /**
   * @memberof V2ConfigurationGet200Response
   * @type {V2ConfigurationGet200ResponseFilters}
   */
  filters?: V2ConfigurationGet200ResponseFilters;
}

/**
 * Check if a given object implements the V2ConfigurationGet200Response
 * interface.
 */
export function instanceOfV2ConfigurationGet200Response(
  value: object
): value is V2ConfigurationGet200Response {
  return true;
}

export function V2ConfigurationGet200ResponseFromJSON(
  json: any
): V2ConfigurationGet200Response {
  return V2ConfigurationGet200ResponseFromJSONTyped(json, false);
}

export function V2ConfigurationGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2ConfigurationGet200Response {
  if (json == null) {
    return json;
  }
  return {
    _configuration:
      json['configuration'] == null ? undefined : json['configuration'],
    can:
      json['can'] == null
        ? undefined
        : V2ConfigurationGet200ResponseCanFromJSON(json['can']),
    defaultTimePeriod:
      json['defaultTimePeriod'] == null
        ? undefined
        : V2ConfigurationGet200ResponseDefaultTimePeriodFromJSON(
            json['defaultTimePeriod']
          ),
    filters:
      json['filters'] == null
        ? undefined
        : V2ConfigurationGet200ResponseFiltersFromJSON(json['filters'])
  };
}

export function V2ConfigurationGet200ResponseToJSON(
  json: any
): V2ConfigurationGet200Response {
  return V2ConfigurationGet200ResponseToJSONTyped(json, false);
}

export function V2ConfigurationGet200ResponseToJSONTyped(
  value?: V2ConfigurationGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    configuration: value['_configuration'],
    can: V2ConfigurationGet200ResponseCanToJSON(value['can']),
    defaultTimePeriod: V2ConfigurationGet200ResponseDefaultTimePeriodToJSON(
      value['defaultTimePeriod']
    ),
    filters: V2ConfigurationGet200ResponseFiltersToJSON(value['filters'])
  };
}
