/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationLinks } from './PaginationLinks';
import {
  PaginationLinksFromJSON,
  PaginationLinksFromJSONTyped,
  PaginationLinksToJSON,
  PaginationLinksToJSONTyped
} from './PaginationLinks';
import type { PaginationMeta } from './PaginationMeta';
import {
  PaginationMetaFromJSON,
  PaginationMetaFromJSONTyped,
  PaginationMetaToJSON,
  PaginationMetaToJSONTyped
} from './PaginationMeta';
import type { V2DatasourcesDatasourceIdProjectPost201ResponseData } from './V2DatasourcesDatasourceIdProjectPost201ResponseData';
import {
  V2DatasourcesDatasourceIdProjectPost201ResponseDataFromJSON,
  V2DatasourcesDatasourceIdProjectPost201ResponseDataFromJSONTyped,
  V2DatasourcesDatasourceIdProjectPost201ResponseDataToJSON,
  V2DatasourcesDatasourceIdProjectPost201ResponseDataToJSONTyped
} from './V2DatasourcesDatasourceIdProjectPost201ResponseData';

/**
 * @export
 * @interface V2DatasourcesProjectsGet200Response
 */
export interface V2DatasourcesProjectsGet200Response {
  /**
   * @memberof V2DatasourcesProjectsGet200Response
   * @type {PaginationLinks}
   */
  links?: PaginationLinks;
  /**
   * @memberof V2DatasourcesProjectsGet200Response
   * @type {PaginationMeta}
   */
  meta?: PaginationMeta;
  /**
   * @memberof V2DatasourcesProjectsGet200Response
   * @type {V2DatasourcesDatasourceIdProjectPost201ResponseData[]}
   */
  data?: Array<V2DatasourcesDatasourceIdProjectPost201ResponseData>;
}

/**
 * Check if a given object implements the V2DatasourcesProjectsGet200Response
 * interface.
 */
export function instanceOfV2DatasourcesProjectsGet200Response(
  value: object
): value is V2DatasourcesProjectsGet200Response {
  return true;
}

export function V2DatasourcesProjectsGet200ResponseFromJSON(
  json: any
): V2DatasourcesProjectsGet200Response {
  return V2DatasourcesProjectsGet200ResponseFromJSONTyped(json, false);
}

export function V2DatasourcesProjectsGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesProjectsGet200Response {
  if (json == null) {
    return json;
  }
  return {
    links:
      json['links'] == null
        ? undefined
        : PaginationLinksFromJSON(json['links']),
    meta:
      json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(
            V2DatasourcesDatasourceIdProjectPost201ResponseDataFromJSON
          )
  };
}

export function V2DatasourcesProjectsGet200ResponseToJSON(
  json: any
): V2DatasourcesProjectsGet200Response {
  return V2DatasourcesProjectsGet200ResponseToJSONTyped(json, false);
}

export function V2DatasourcesProjectsGet200ResponseToJSONTyped(
  value?: V2DatasourcesProjectsGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    links: PaginationLinksToJSON(value['links']),
    meta: PaginationMetaToJSON(value['meta']),
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(
            V2DatasourcesDatasourceIdProjectPost201ResponseDataToJSON
          )
  };
}
