/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseData } from './V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseData';
import {
  V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseDataFromJSON,
  V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseDataFromJSONTyped,
  V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseDataToJSON,
  V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseDataToJSONTyped
} from './V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseData';

/**
 * @export
 * @interface V2DatasourcesResourcesResourceIdResourceSlugGet200Response
 */
export interface V2DatasourcesResourcesResourceIdResourceSlugGet200Response {
  /**
   * @memberof V2DatasourcesResourcesResourceIdResourceSlugGet200Response
   * @type {V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseData}
   */
  data?: V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseData;
}

/**
 * Check if a given object implements the
 * V2DatasourcesResourcesResourceIdResourceSlugGet200Response interface.
 */
export function instanceOfV2DatasourcesResourcesResourceIdResourceSlugGet200Response(
  value: object
): value is V2DatasourcesResourcesResourceIdResourceSlugGet200Response {
  return true;
}

export function V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseFromJSON(
  json: any
): V2DatasourcesResourcesResourceIdResourceSlugGet200Response {
  return V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseFromJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesResourcesResourceIdResourceSlugGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseDataFromJSON(
            json['data']
          )
  };
}

export function V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseToJSON(
  json: any
): V2DatasourcesResourcesResourceIdResourceSlugGet200Response {
  return V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseToJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseToJSONTyped(
  value?: V2DatasourcesResourcesResourceIdResourceSlugGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseDataToJSON(
      value['data']
    )
  };
}
