/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface V2DatasourcesPhasesPhaseIdGet200ResponseData
 */
export interface V2DatasourcesPhasesPhaseIdGet200ResponseData {
  /**
   * @memberof V2DatasourcesPhasesPhaseIdGet200ResponseData
   * @type {number}
   */
  id?: number;
  /**
   * @memberof V2DatasourcesPhasesPhaseIdGet200ResponseData
   * @type {string}
   */
  slug?: string;
  /**
   * @memberof V2DatasourcesPhasesPhaseIdGet200ResponseData
   * @type {number}
   */
  projectId?: number;
  /**
   * @memberof V2DatasourcesPhasesPhaseIdGet200ResponseData
   * @type {Date}
   */
  start?: Date | null;
  /**
   * @memberof V2DatasourcesPhasesPhaseIdGet200ResponseData
   * @type {Date}
   */
  end?: Date | null;
  /**
   * @memberof V2DatasourcesPhasesPhaseIdGet200ResponseData
   * @type {boolean}
   */
  isStaged?: boolean;
  /**
   * @memberof V2DatasourcesPhasesPhaseIdGet200ResponseData
   * @type {Date}
   */
  createdAt?: Date;
  /**
   * @memberof V2DatasourcesPhasesPhaseIdGet200ResponseData
   * @type {Date}
   */
  updatedAt?: Date;
}

/**
 * Check if a given object implements the
 * V2DatasourcesPhasesPhaseIdGet200ResponseData interface.
 */
export function instanceOfV2DatasourcesPhasesPhaseIdGet200ResponseData(
  value: object
): value is V2DatasourcesPhasesPhaseIdGet200ResponseData {
  return true;
}

export function V2DatasourcesPhasesPhaseIdGet200ResponseDataFromJSON(
  json: any
): V2DatasourcesPhasesPhaseIdGet200ResponseData {
  return V2DatasourcesPhasesPhaseIdGet200ResponseDataFromJSONTyped(json, false);
}

export function V2DatasourcesPhasesPhaseIdGet200ResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesPhasesPhaseIdGet200ResponseData {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    slug: json['slug'] == null ? undefined : json['slug'],
    projectId: json['project_id'] == null ? undefined : json['project_id'],
    start: json['start'] == null ? undefined : new Date(json['start']),
    end: json['end'] == null ? undefined : new Date(json['end']),
    isStaged: json['is_staged'] == null ? undefined : json['is_staged'],
    createdAt:
      json['created_at'] == null ? undefined : new Date(json['created_at']),
    updatedAt:
      json['updated_at'] == null ? undefined : new Date(json['updated_at'])
  };
}

export function V2DatasourcesPhasesPhaseIdGet200ResponseDataToJSON(
  json: any
): V2DatasourcesPhasesPhaseIdGet200ResponseData {
  return V2DatasourcesPhasesPhaseIdGet200ResponseDataToJSONTyped(json, false);
}

export function V2DatasourcesPhasesPhaseIdGet200ResponseDataToJSONTyped(
  value?: V2DatasourcesPhasesPhaseIdGet200ResponseData | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    slug: value['slug'],
    project_id: value['projectId'],
    start:
      value['start'] == null
        ? undefined
        : (value['start'] as any).toISOString(),
    end: value['end'] == null ? undefined : (value['end'] as any).toISOString(),
    is_staged: value['isStaged'],
    created_at:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updated_at:
      value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString()
  };
}
