/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { V2DatasourcesDatasourceIdProjectPost422ResponseErrors } from './V2DatasourcesDatasourceIdProjectPost422ResponseErrors';
import {
  V2DatasourcesDatasourceIdProjectPost422ResponseErrorsFromJSON,
  V2DatasourcesDatasourceIdProjectPost422ResponseErrorsFromJSONTyped,
  V2DatasourcesDatasourceIdProjectPost422ResponseErrorsToJSON,
  V2DatasourcesDatasourceIdProjectPost422ResponseErrorsToJSONTyped
} from './V2DatasourcesDatasourceIdProjectPost422ResponseErrors';

/**
 * @export
 * @interface V2DatasourcesDatasourceIdProjectPost422Response
 */
export interface V2DatasourcesDatasourceIdProjectPost422Response {
  /**
   * First validation error or general message
   *
   * @memberof V2DatasourcesDatasourceIdProjectPost422Response
   * @type {string}
   */
  message?: string;
  /**
   * @memberof V2DatasourcesDatasourceIdProjectPost422Response
   * @type {V2DatasourcesDatasourceIdProjectPost422ResponseErrors}
   */
  errors?: V2DatasourcesDatasourceIdProjectPost422ResponseErrors;
}

/**
 * Check if a given object implements the
 * V2DatasourcesDatasourceIdProjectPost422Response interface.
 */
export function instanceOfV2DatasourcesDatasourceIdProjectPost422Response(
  value: object
): value is V2DatasourcesDatasourceIdProjectPost422Response {
  return true;
}

export function V2DatasourcesDatasourceIdProjectPost422ResponseFromJSON(
  json: any
): V2DatasourcesDatasourceIdProjectPost422Response {
  return V2DatasourcesDatasourceIdProjectPost422ResponseFromJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesDatasourceIdProjectPost422ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesDatasourceIdProjectPost422Response {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'] == null ? undefined : json['message'],
    errors:
      json['errors'] == null
        ? undefined
        : V2DatasourcesDatasourceIdProjectPost422ResponseErrorsFromJSON(
            json['errors']
          )
  };
}

export function V2DatasourcesDatasourceIdProjectPost422ResponseToJSON(
  json: any
): V2DatasourcesDatasourceIdProjectPost422Response {
  return V2DatasourcesDatasourceIdProjectPost422ResponseToJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesDatasourceIdProjectPost422ResponseToJSONTyped(
  value?: V2DatasourcesDatasourceIdProjectPost422Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    errors: V2DatasourcesDatasourceIdProjectPost422ResponseErrorsToJSON(
      value['errors']
    )
  };
}
