/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner } from './V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner';
import {
  V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInnerFromJSON,
  V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInnerFromJSONTyped,
  V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInnerToJSON,
  V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInnerToJSONTyped
} from './V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner';

/**
 * @export
 * @interface V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200Response
 */
export interface V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200Response {
  /**
   * @memberof V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200Response
   * @type {V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner[]}
   */
  data?: Array<V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner>;
}

/**
 * Check if a given object implements the
 * V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200Response
 * interface.
 */
export function instanceOfV2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200Response(
  value: object
): value is V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200Response {
  return true;
}

export function V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseFromJSON(
  json: any
): V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200Response {
  return V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseFromJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(
            V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInnerFromJSON
          )
  };
}

export function V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseToJSON(
  json: any
): V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200Response {
  return V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseToJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseToJSONTyped(
  value?: V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(
            V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInnerToJSON
          )
  };
}
