/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { DatasourceEntry } from './DatasourceEntry';
import {
  DatasourceEntryFromJSON,
  DatasourceEntryFromJSONTyped,
  DatasourceEntryToJSON,
  DatasourceEntryToJSONTyped
} from './DatasourceEntry';

/**
 * @export
 * @interface V2DatasourcesDatasourceIdEntriesEntryIdGet200Response
 */
export interface V2DatasourcesDatasourceIdEntriesEntryIdGet200Response {
  /**
   * @memberof V2DatasourcesDatasourceIdEntriesEntryIdGet200Response
   * @type {DatasourceEntry}
   */
  data?: DatasourceEntry;
}

/**
 * Check if a given object implements the
 * V2DatasourcesDatasourceIdEntriesEntryIdGet200Response interface.
 */
export function instanceOfV2DatasourcesDatasourceIdEntriesEntryIdGet200Response(
  value: object
): value is V2DatasourcesDatasourceIdEntriesEntryIdGet200Response {
  return true;
}

export function V2DatasourcesDatasourceIdEntriesEntryIdGet200ResponseFromJSON(
  json: any
): V2DatasourcesDatasourceIdEntriesEntryIdGet200Response {
  return V2DatasourcesDatasourceIdEntriesEntryIdGet200ResponseFromJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesDatasourceIdEntriesEntryIdGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesDatasourceIdEntriesEntryIdGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null ? undefined : DatasourceEntryFromJSON(json['data'])
  };
}

export function V2DatasourcesDatasourceIdEntriesEntryIdGet200ResponseToJSON(
  json: any
): V2DatasourcesDatasourceIdEntriesEntryIdGet200Response {
  return V2DatasourcesDatasourceIdEntriesEntryIdGet200ResponseToJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesDatasourceIdEntriesEntryIdGet200ResponseToJSONTyped(
  value?: V2DatasourcesDatasourceIdEntriesEntryIdGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: DatasourceEntryToJSON(value['data'])
  };
}
