/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { V2DatasourcesProjectsProjectIdGet200ResponseData } from './V2DatasourcesProjectsProjectIdGet200ResponseData';
import {
  V2DatasourcesProjectsProjectIdGet200ResponseDataFromJSON,
  V2DatasourcesProjectsProjectIdGet200ResponseDataFromJSONTyped,
  V2DatasourcesProjectsProjectIdGet200ResponseDataToJSON,
  V2DatasourcesProjectsProjectIdGet200ResponseDataToJSONTyped
} from './V2DatasourcesProjectsProjectIdGet200ResponseData';

/**
 * @export
 * @interface V2DatasourcesProjectsProjectIdGet200Response
 */
export interface V2DatasourcesProjectsProjectIdGet200Response {
  /**
   * @memberof V2DatasourcesProjectsProjectIdGet200Response
   * @type {V2DatasourcesProjectsProjectIdGet200ResponseData}
   */
  data?: V2DatasourcesProjectsProjectIdGet200ResponseData;
}

/**
 * Check if a given object implements the
 * V2DatasourcesProjectsProjectIdGet200Response interface.
 */
export function instanceOfV2DatasourcesProjectsProjectIdGet200Response(
  value: object
): value is V2DatasourcesProjectsProjectIdGet200Response {
  return true;
}

export function V2DatasourcesProjectsProjectIdGet200ResponseFromJSON(
  json: any
): V2DatasourcesProjectsProjectIdGet200Response {
  return V2DatasourcesProjectsProjectIdGet200ResponseFromJSONTyped(json, false);
}

export function V2DatasourcesProjectsProjectIdGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesProjectsProjectIdGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : V2DatasourcesProjectsProjectIdGet200ResponseDataFromJSON(json['data'])
  };
}

export function V2DatasourcesProjectsProjectIdGet200ResponseToJSON(
  json: any
): V2DatasourcesProjectsProjectIdGet200Response {
  return V2DatasourcesProjectsProjectIdGet200ResponseToJSONTyped(json, false);
}

export function V2DatasourcesProjectsProjectIdGet200ResponseToJSONTyped(
  value?: V2DatasourcesProjectsProjectIdGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: V2DatasourcesProjectsProjectIdGet200ResponseDataToJSON(value['data'])
  };
}
