/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { V2DatasourcesResourcesGet200ResponseAllOfDataInner } from './V2DatasourcesResourcesGet200ResponseAllOfDataInner';
import {
  V2DatasourcesResourcesGet200ResponseAllOfDataInnerFromJSON,
  V2DatasourcesResourcesGet200ResponseAllOfDataInnerFromJSONTyped,
  V2DatasourcesResourcesGet200ResponseAllOfDataInnerToJSON,
  V2DatasourcesResourcesGet200ResponseAllOfDataInnerToJSONTyped
} from './V2DatasourcesResourcesGet200ResponseAllOfDataInner';
import type { PaginationLinks } from './PaginationLinks';
import {
  PaginationLinksFromJSON,
  PaginationLinksFromJSONTyped,
  PaginationLinksToJSON,
  PaginationLinksToJSONTyped
} from './PaginationLinks';
import type { PaginationMeta } from './PaginationMeta';
import {
  PaginationMetaFromJSON,
  PaginationMetaFromJSONTyped,
  PaginationMetaToJSON,
  PaginationMetaToJSONTyped
} from './PaginationMeta';

/**
 * @export
 * @interface V2DatasourcesResourcesGet200Response
 */
export interface V2DatasourcesResourcesGet200Response {
  /**
   * @memberof V2DatasourcesResourcesGet200Response
   * @type {PaginationLinks}
   */
  links?: PaginationLinks;
  /**
   * @memberof V2DatasourcesResourcesGet200Response
   * @type {PaginationMeta}
   */
  meta?: PaginationMeta;
  /**
   * @memberof V2DatasourcesResourcesGet200Response
   * @type {V2DatasourcesResourcesGet200ResponseAllOfDataInner[]}
   */
  data?: Array<V2DatasourcesResourcesGet200ResponseAllOfDataInner>;
}

/**
 * Check if a given object implements the V2DatasourcesResourcesGet200Response
 * interface.
 */
export function instanceOfV2DatasourcesResourcesGet200Response(
  value: object
): value is V2DatasourcesResourcesGet200Response {
  return true;
}

export function V2DatasourcesResourcesGet200ResponseFromJSON(
  json: any
): V2DatasourcesResourcesGet200Response {
  return V2DatasourcesResourcesGet200ResponseFromJSONTyped(json, false);
}

export function V2DatasourcesResourcesGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesResourcesGet200Response {
  if (json == null) {
    return json;
  }
  return {
    links:
      json['links'] == null
        ? undefined
        : PaginationLinksFromJSON(json['links']),
    meta:
      json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(
            V2DatasourcesResourcesGet200ResponseAllOfDataInnerFromJSON
          )
  };
}

export function V2DatasourcesResourcesGet200ResponseToJSON(
  json: any
): V2DatasourcesResourcesGet200Response {
  return V2DatasourcesResourcesGet200ResponseToJSONTyped(json, false);
}

export function V2DatasourcesResourcesGet200ResponseToJSONTyped(
  value?: V2DatasourcesResourcesGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    links: PaginationLinksToJSON(value['links']),
    meta: PaginationMetaToJSON(value['meta']),
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(
            V2DatasourcesResourcesGet200ResponseAllOfDataInnerToJSON
          )
  };
}
