/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface V2DatasourcesAllocationsMultipleGet500Response
 */
export interface V2DatasourcesAllocationsMultipleGet500Response {
  /**
   * Developer oriented error message
   *
   * @memberof V2DatasourcesAllocationsMultipleGet500Response
   * @type {string}
   */
  message?: string;
}

/**
 * Check if a given object implements the
 * V2DatasourcesAllocationsMultipleGet500Response interface.
 */
export function instanceOfV2DatasourcesAllocationsMultipleGet500Response(
  value: object
): value is V2DatasourcesAllocationsMultipleGet500Response {
  return true;
}

export function V2DatasourcesAllocationsMultipleGet500ResponseFromJSON(
  json: any
): V2DatasourcesAllocationsMultipleGet500Response {
  return V2DatasourcesAllocationsMultipleGet500ResponseFromJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesAllocationsMultipleGet500ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesAllocationsMultipleGet500Response {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'] == null ? undefined : json['message']
  };
}

export function V2DatasourcesAllocationsMultipleGet500ResponseToJSON(
  json: any
): V2DatasourcesAllocationsMultipleGet500Response {
  return V2DatasourcesAllocationsMultipleGet500ResponseToJSONTyped(json, false);
}

export function V2DatasourcesAllocationsMultipleGet500ResponseToJSONTyped(
  value?: V2DatasourcesAllocationsMultipleGet500Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message']
  };
}
