/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { DatasourceAllocation } from './DatasourceAllocation';
import {
  DatasourceAllocationFromJSON,
  DatasourceAllocationFromJSONTyped,
  DatasourceAllocationToJSON,
  DatasourceAllocationToJSONTyped
} from './DatasourceAllocation';

/**
 * @export
 * @interface V2DatasourcesAllocationsMultiplePut201Response
 */
export interface V2DatasourcesAllocationsMultiplePut201Response {
  /**
   * @memberof V2DatasourcesAllocationsMultiplePut201Response
   * @type {DatasourceAllocation[]}
   */
  data?: Array<DatasourceAllocation>;
}

/**
 * Check if a given object implements the
 * V2DatasourcesAllocationsMultiplePut201Response interface.
 */
export function instanceOfV2DatasourcesAllocationsMultiplePut201Response(
  value: object
): value is V2DatasourcesAllocationsMultiplePut201Response {
  return true;
}

export function V2DatasourcesAllocationsMultiplePut201ResponseFromJSON(
  json: any
): V2DatasourcesAllocationsMultiplePut201Response {
  return V2DatasourcesAllocationsMultiplePut201ResponseFromJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesAllocationsMultiplePut201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesAllocationsMultiplePut201Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(DatasourceAllocationFromJSON)
  };
}

export function V2DatasourcesAllocationsMultiplePut201ResponseToJSON(
  json: any
): V2DatasourcesAllocationsMultiplePut201Response {
  return V2DatasourcesAllocationsMultiplePut201ResponseToJSONTyped(json, false);
}

export function V2DatasourcesAllocationsMultiplePut201ResponseToJSONTyped(
  value?: V2DatasourcesAllocationsMultiplePut201Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(DatasourceAllocationToJSON)
  };
}
