/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface V2DatasourcesResourcesGet200ResponseAllOfDataInner
 */
export interface V2DatasourcesResourcesGet200ResponseAllOfDataInner {
  /**
   * @memberof V2DatasourcesResourcesGet200ResponseAllOfDataInner
   * @type {number}
   */
  id?: number;
  /**
   * Use this field to display to the user
   *
   * @memberof V2DatasourcesResourcesGet200ResponseAllOfDataInner
   * @type {string}
   */
  label?: string;
  /**
   * @memberof V2DatasourcesResourcesGet200ResponseAllOfDataInner
   * @type {string}
   */
  name?: string;
  /**
   * This is the name field slugified
   *
   * @memberof V2DatasourcesResourcesGet200ResponseAllOfDataInner
   * @type {string}
   */
  slug?: string;
  /**
   * @memberof V2DatasourcesResourcesGet200ResponseAllOfDataInner
   * @type {Date}
   */
  createdAt?: Date;
  /**
   * @memberof V2DatasourcesResourcesGet200ResponseAllOfDataInner
   * @type {Date}
   */
  updatedAt?: Date;
}

/**
 * Check if a given object implements the
 * V2DatasourcesResourcesGet200ResponseAllOfDataInner interface.
 */
export function instanceOfV2DatasourcesResourcesGet200ResponseAllOfDataInner(
  value: object
): value is V2DatasourcesResourcesGet200ResponseAllOfDataInner {
  return true;
}

export function V2DatasourcesResourcesGet200ResponseAllOfDataInnerFromJSON(
  json: any
): V2DatasourcesResourcesGet200ResponseAllOfDataInner {
  return V2DatasourcesResourcesGet200ResponseAllOfDataInnerFromJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesResourcesGet200ResponseAllOfDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesResourcesGet200ResponseAllOfDataInner {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    label: json['label'] == null ? undefined : json['label'],
    name: json['name'] == null ? undefined : json['name'],
    slug: json['slug'] == null ? undefined : json['slug'],
    createdAt:
      json['created_at'] == null ? undefined : new Date(json['created_at']),
    updatedAt:
      json['updated_at'] == null ? undefined : new Date(json['updated_at'])
  };
}

export function V2DatasourcesResourcesGet200ResponseAllOfDataInnerToJSON(
  json: any
): V2DatasourcesResourcesGet200ResponseAllOfDataInner {
  return V2DatasourcesResourcesGet200ResponseAllOfDataInnerToJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesResourcesGet200ResponseAllOfDataInnerToJSONTyped(
  value?: V2DatasourcesResourcesGet200ResponseAllOfDataInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    label: value['label'],
    name: value['name'],
    slug: value['slug'],
    created_at:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updated_at:
      value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString()
  };
}
