/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface V2DatasourcesDatasourceIdProjectPost422ResponseErrors
 */
export interface V2DatasourcesDatasourceIdProjectPost422ResponseErrors {
  /**
   * List with one or more problems that this key has
   *
   * @memberof V2DatasourcesDatasourceIdProjectPost422ResponseErrors
   * @type {string[]}
   */
  keyOfParameterThatFailedValidation?: Array<string>;
}

/**
 * Check if a given object implements the
 * V2DatasourcesDatasourceIdProjectPost422ResponseErrors interface.
 */
export function instanceOfV2DatasourcesDatasourceIdProjectPost422ResponseErrors(
  value: object
): value is V2DatasourcesDatasourceIdProjectPost422ResponseErrors {
  return true;
}

export function V2DatasourcesDatasourceIdProjectPost422ResponseErrorsFromJSON(
  json: any
): V2DatasourcesDatasourceIdProjectPost422ResponseErrors {
  return V2DatasourcesDatasourceIdProjectPost422ResponseErrorsFromJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesDatasourceIdProjectPost422ResponseErrorsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesDatasourceIdProjectPost422ResponseErrors {
  if (json == null) {
    return json;
  }
  return {
    keyOfParameterThatFailedValidation:
      json['&lt;key-of-parameter-that-failed-validation&gt;'] == null
        ? undefined
        : json['&lt;key-of-parameter-that-failed-validation&gt;']
  };
}

export function V2DatasourcesDatasourceIdProjectPost422ResponseErrorsToJSON(
  json: any
): V2DatasourcesDatasourceIdProjectPost422ResponseErrors {
  return V2DatasourcesDatasourceIdProjectPost422ResponseErrorsToJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesDatasourceIdProjectPost422ResponseErrorsToJSONTyped(
  value?: V2DatasourcesDatasourceIdProjectPost422ResponseErrors | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    '&lt;key-of-parameter-that-failed-validation&gt;':
      value['keyOfParameterThatFailedValidation']
  };
}
