/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { AllocationTypesAllocationTypesInner } from './AllocationTypesAllocationTypesInner';
import {
  AllocationTypesAllocationTypesInnerFromJSON,
  AllocationTypesAllocationTypesInnerFromJSONTyped,
  AllocationTypesAllocationTypesInnerToJSON,
  AllocationTypesAllocationTypesInnerToJSONTyped
} from './AllocationTypesAllocationTypesInner';
import type { EntityDatumProjectResourceAllocationsGroupedInner } from './EntityDatumProjectResourceAllocationsGroupedInner';
import {
  EntityDatumProjectResourceAllocationsGroupedInnerFromJSON,
  EntityDatumProjectResourceAllocationsGroupedInnerFromJSONTyped,
  EntityDatumProjectResourceAllocationsGroupedInnerToJSON,
  EntityDatumProjectResourceAllocationsGroupedInnerToJSONTyped
} from './EntityDatumProjectResourceAllocationsGroupedInner';

/**
 * @export
 * @interface V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner
 */
export interface V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner {
  /**
   * @memberof V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner
   * @type {number}
   */
  id?: number;
  /**
   * Use this field to display to the user
   *
   * @memberof V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner
   * @type {string}
   */
  label?: string;
  /**
   * @memberof V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner
   * @type {string}
   */
  name?: string;
  /**
   * This is the name field slugified
   *
   * @memberof V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner
   * @type {string}
   */
  slug?: string;
  /**
   * @memberof V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner
   * @type {EntityDatumProjectResourceAllocationsGroupedInner[]}
   */
  allocationsGrouped?: Array<EntityDatumProjectResourceAllocationsGroupedInner>;
  /**
   * @memberof V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner
   * @type {AllocationTypesAllocationTypesInner[]}
   */
  allocationTypes?: Array<AllocationTypesAllocationTypesInner> | null;
  /**
   * @memberof V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner
   * @type {Date}
   */
  createdAt?: Date;
  /**
   * @memberof V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner
   * @type {Date}
   */
  updatedAt?: Date;
}

/**
 * Check if a given object implements the
 * V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner
 * interface.
 */
export function instanceOfV2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner(
  value: object
): value is V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner {
  return true;
}

export function V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInnerFromJSON(
  json: any
): V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner {
  return V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInnerFromJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    label: json['label'] == null ? undefined : json['label'],
    name: json['name'] == null ? undefined : json['name'],
    slug: json['slug'] == null ? undefined : json['slug'],
    allocationsGrouped:
      json['allocations_grouped'] == null
        ? undefined
        : (json['allocations_grouped'] as Array<any>).map(
            EntityDatumProjectResourceAllocationsGroupedInnerFromJSON
          ),
    allocationTypes:
      json['allocation_types'] == null
        ? undefined
        : (json['allocation_types'] as Array<any>).map(
            AllocationTypesAllocationTypesInnerFromJSON
          ),
    createdAt:
      json['created_at'] == null ? undefined : new Date(json['created_at']),
    updatedAt:
      json['updated_at'] == null ? undefined : new Date(json['updated_at'])
  };
}

export function V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInnerToJSON(
  json: any
): V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner {
  return V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInnerToJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInnerToJSONTyped(
  value?: V2DatasourcesResourcesResourceIdProjectsDatasourceSlugGet200ResponseDataInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    label: value['label'],
    name: value['name'],
    slug: value['slug'],
    allocations_grouped:
      value['allocationsGrouped'] == null
        ? undefined
        : (value['allocationsGrouped'] as Array<any>).map(
            EntityDatumProjectResourceAllocationsGroupedInnerToJSON
          ),
    allocation_types:
      value['allocationTypes'] == null
        ? undefined
        : (value['allocationTypes'] as Array<any>).map(
            AllocationTypesAllocationTypesInnerToJSON
          ),
    created_at:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updated_at:
      value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString()
  };
}
