/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { Datasource } from './Datasource';
import {
  DatasourceFromJSON,
  DatasourceFromJSONTyped,
  DatasourceToJSON,
  DatasourceToJSONTyped
} from './Datasource';

/**
 * @export
 * @interface V2DatasourcesDatasourceIdGet200Response
 */
export interface V2DatasourcesDatasourceIdGet200Response {
  /**
   * @memberof V2DatasourcesDatasourceIdGet200Response
   * @type {Datasource}
   */
  data?: Datasource;
}

/**
 * Check if a given object implements the
 * V2DatasourcesDatasourceIdGet200Response interface.
 */
export function instanceOfV2DatasourcesDatasourceIdGet200Response(
  value: object
): value is V2DatasourcesDatasourceIdGet200Response {
  return true;
}

export function V2DatasourcesDatasourceIdGet200ResponseFromJSON(
  json: any
): V2DatasourcesDatasourceIdGet200Response {
  return V2DatasourcesDatasourceIdGet200ResponseFromJSONTyped(json, false);
}

export function V2DatasourcesDatasourceIdGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesDatasourceIdGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : DatasourceFromJSON(json['data'])
  };
}

export function V2DatasourcesDatasourceIdGet200ResponseToJSON(
  json: any
): V2DatasourcesDatasourceIdGet200Response {
  return V2DatasourcesDatasourceIdGet200ResponseToJSONTyped(json, false);
}

export function V2DatasourcesDatasourceIdGet200ResponseToJSONTyped(
  value?: V2DatasourcesDatasourceIdGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: DatasourceToJSON(value['data'])
  };
}
