/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { DatasourceAllocation } from './DatasourceAllocation';
import {
  DatasourceAllocationFromJSON,
  DatasourceAllocationFromJSONTyped,
  DatasourceAllocationToJSON,
  DatasourceAllocationToJSONTyped
} from './DatasourceAllocation';

/**
 * @export
 * @interface V2DatasourcesAllocationsMultipleGet200Response
 */
export interface V2DatasourcesAllocationsMultipleGet200Response {
  /**
   * @memberof V2DatasourcesAllocationsMultipleGet200Response
   * @type {DatasourceAllocation[]}
   */
  data?: Array<DatasourceAllocation>;
}

/**
 * Check if a given object implements the
 * V2DatasourcesAllocationsMultipleGet200Response interface.
 */
export function instanceOfV2DatasourcesAllocationsMultipleGet200Response(
  value: object
): value is V2DatasourcesAllocationsMultipleGet200Response {
  return true;
}

export function V2DatasourcesAllocationsMultipleGet200ResponseFromJSON(
  json: any
): V2DatasourcesAllocationsMultipleGet200Response {
  return V2DatasourcesAllocationsMultipleGet200ResponseFromJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesAllocationsMultipleGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesAllocationsMultipleGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(DatasourceAllocationFromJSON)
  };
}

export function V2DatasourcesAllocationsMultipleGet200ResponseToJSON(
  json: any
): V2DatasourcesAllocationsMultipleGet200Response {
  return V2DatasourcesAllocationsMultipleGet200ResponseToJSONTyped(json, false);
}

export function V2DatasourcesAllocationsMultipleGet200ResponseToJSONTyped(
  value?: V2DatasourcesAllocationsMultipleGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(DatasourceAllocationToJSON)
  };
}
