/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceDataEntry } from './ResourceDataEntry';
import {
  ResourceDataEntryFromJSON,
  ResourceDataEntryFromJSONTyped,
  ResourceDataEntryToJSON,
  ResourceDataEntryToJSONTyped
} from './ResourceDataEntry';

/**
 * @export
 * @interface V2DatasourcesResourcesResourceIdResourceSlugGet200Response
 */
export interface V2DatasourcesResourcesResourceIdResourceSlugGet200Response {
  /**
   * @memberof V2DatasourcesResourcesResourceIdResourceSlugGet200Response
   * @type {number}
   */
  id?: number;
  /**
   * Use this field to display to the user
   *
   * @memberof V2DatasourcesResourcesResourceIdResourceSlugGet200Response
   * @type {string}
   */
  label?: string;
  /**
   * @memberof V2DatasourcesResourcesResourceIdResourceSlugGet200Response
   * @type {string}
   */
  name?: string;
  /**
   * This is the name field slugified
   *
   * @memberof V2DatasourcesResourcesResourceIdResourceSlugGet200Response
   * @type {string}
   */
  slug?: string;
  /**
   * @memberof V2DatasourcesResourcesResourceIdResourceSlugGet200Response
   * @type {Date}
   */
  createdAt?: Date;
  /**
   * @memberof V2DatasourcesResourcesResourceIdResourceSlugGet200Response
   * @type {Date}
   */
  updatedAt?: Date;
  /**
   * @memberof V2DatasourcesResourcesResourceIdResourceSlugGet200Response
   * @type {ResourceDataEntry[]}
   */
  data?: Array<ResourceDataEntry>;
}

/**
 * Check if a given object implements the
 * V2DatasourcesResourcesResourceIdResourceSlugGet200Response interface.
 */
export function instanceOfV2DatasourcesResourcesResourceIdResourceSlugGet200Response(
  value: object
): value is V2DatasourcesResourcesResourceIdResourceSlugGet200Response {
  return true;
}

export function V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseFromJSON(
  json: any
): V2DatasourcesResourcesResourceIdResourceSlugGet200Response {
  return V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseFromJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesResourcesResourceIdResourceSlugGet200Response {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    label: json['label'] == null ? undefined : json['label'],
    name: json['name'] == null ? undefined : json['name'],
    slug: json['slug'] == null ? undefined : json['slug'],
    createdAt:
      json['created_at'] == null ? undefined : new Date(json['created_at']),
    updatedAt:
      json['updated_at'] == null ? undefined : new Date(json['updated_at']),
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(ResourceDataEntryFromJSON)
  };
}

export function V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseToJSON(
  json: any
): V2DatasourcesResourcesResourceIdResourceSlugGet200Response {
  return V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseToJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesResourcesResourceIdResourceSlugGet200ResponseToJSONTyped(
  value?: V2DatasourcesResourcesResourceIdResourceSlugGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    label: value['label'],
    name: value['name'],
    slug: value['slug'],
    created_at:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updated_at:
      value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString(),
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(ResourceDataEntryToJSON)
  };
}
