/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationLinks } from './PaginationLinks';
import {
  PaginationLinksFromJSON,
  PaginationLinksFromJSONTyped,
  PaginationLinksToJSON,
  PaginationLinksToJSONTyped
} from './PaginationLinks';
import type { PaginationMeta } from './PaginationMeta';
import {
  PaginationMetaFromJSON,
  PaginationMetaFromJSONTyped,
  PaginationMetaToJSON,
  PaginationMetaToJSONTyped
} from './PaginationMeta';
import type { V2DatasourcesPhasesPhaseIdGet200ResponseData } from './V2DatasourcesPhasesPhaseIdGet200ResponseData';
import {
  V2DatasourcesPhasesPhaseIdGet200ResponseDataFromJSON,
  V2DatasourcesPhasesPhaseIdGet200ResponseDataFromJSONTyped,
  V2DatasourcesPhasesPhaseIdGet200ResponseDataToJSON,
  V2DatasourcesPhasesPhaseIdGet200ResponseDataToJSONTyped
} from './V2DatasourcesPhasesPhaseIdGet200ResponseData';

/**
 * @export
 * @interface V2DatasourcesProjectProjectIdPhasesGet200Response
 */
export interface V2DatasourcesProjectProjectIdPhasesGet200Response {
  /**
   * @memberof V2DatasourcesProjectProjectIdPhasesGet200Response
   * @type {PaginationLinks}
   */
  links?: PaginationLinks;
  /**
   * @memberof V2DatasourcesProjectProjectIdPhasesGet200Response
   * @type {PaginationMeta}
   */
  meta?: PaginationMeta;
  /**
   * @memberof V2DatasourcesProjectProjectIdPhasesGet200Response
   * @type {V2DatasourcesPhasesPhaseIdGet200ResponseData[]}
   */
  data?: Array<V2DatasourcesPhasesPhaseIdGet200ResponseData>;
}

/**
 * Check if a given object implements the
 * V2DatasourcesProjectProjectIdPhasesGet200Response interface.
 */
export function instanceOfV2DatasourcesProjectProjectIdPhasesGet200Response(
  value: object
): value is V2DatasourcesProjectProjectIdPhasesGet200Response {
  return true;
}

export function V2DatasourcesProjectProjectIdPhasesGet200ResponseFromJSON(
  json: any
): V2DatasourcesProjectProjectIdPhasesGet200Response {
  return V2DatasourcesProjectProjectIdPhasesGet200ResponseFromJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesProjectProjectIdPhasesGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesProjectProjectIdPhasesGet200Response {
  if (json == null) {
    return json;
  }
  return {
    links:
      json['links'] == null
        ? undefined
        : PaginationLinksFromJSON(json['links']),
    meta:
      json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(
            V2DatasourcesPhasesPhaseIdGet200ResponseDataFromJSON
          )
  };
}

export function V2DatasourcesProjectProjectIdPhasesGet200ResponseToJSON(
  json: any
): V2DatasourcesProjectProjectIdPhasesGet200Response {
  return V2DatasourcesProjectProjectIdPhasesGet200ResponseToJSONTyped(
    json,
    false
  );
}

export function V2DatasourcesProjectProjectIdPhasesGet200ResponseToJSONTyped(
  value?: V2DatasourcesProjectProjectIdPhasesGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    links: PaginationLinksToJSON(value['links']),
    meta: PaginationMetaToJSON(value['meta']),
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(
            V2DatasourcesPhasesPhaseIdGet200ResponseDataToJSON
          )
  };
}
