/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { V2DatasourcesPhasesPhaseIdGet200ResponseData } from './V2DatasourcesPhasesPhaseIdGet200ResponseData';
import {
  V2DatasourcesPhasesPhaseIdGet200ResponseDataFromJSON,
  V2DatasourcesPhasesPhaseIdGet200ResponseDataFromJSONTyped,
  V2DatasourcesPhasesPhaseIdGet200ResponseDataToJSON,
  V2DatasourcesPhasesPhaseIdGet200ResponseDataToJSONTyped
} from './V2DatasourcesPhasesPhaseIdGet200ResponseData';

/**
 * @export
 * @interface V2DatasourcesPhasesPhaseIdGet200Response
 */
export interface V2DatasourcesPhasesPhaseIdGet200Response {
  /**
   * @memberof V2DatasourcesPhasesPhaseIdGet200Response
   * @type {V2DatasourcesPhasesPhaseIdGet200ResponseData}
   */
  data?: V2DatasourcesPhasesPhaseIdGet200ResponseData;
}

/**
 * Check if a given object implements the
 * V2DatasourcesPhasesPhaseIdGet200Response interface.
 */
export function instanceOfV2DatasourcesPhasesPhaseIdGet200Response(
  value: object
): value is V2DatasourcesPhasesPhaseIdGet200Response {
  return true;
}

export function V2DatasourcesPhasesPhaseIdGet200ResponseFromJSON(
  json: any
): V2DatasourcesPhasesPhaseIdGet200Response {
  return V2DatasourcesPhasesPhaseIdGet200ResponseFromJSONTyped(json, false);
}

export function V2DatasourcesPhasesPhaseIdGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): V2DatasourcesPhasesPhaseIdGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : V2DatasourcesPhasesPhaseIdGet200ResponseDataFromJSON(json['data'])
  };
}

export function V2DatasourcesPhasesPhaseIdGet200ResponseToJSON(
  json: any
): V2DatasourcesPhasesPhaseIdGet200Response {
  return V2DatasourcesPhasesPhaseIdGet200ResponseToJSONTyped(json, false);
}

export function V2DatasourcesPhasesPhaseIdGet200ResponseToJSONTyped(
  value?: V2DatasourcesPhasesPhaseIdGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: V2DatasourcesPhasesPhaseIdGet200ResponseDataToJSON(value['data'])
  };
}
