/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface WorkedDays
 */
export interface WorkedDays {
  /**
   * @memberof WorkedDays
   * @type {number}
   */
  worked?: number | null;
  /**
   * @memberof WorkedDays
   * @type {number}
   */
  max?: number | null;
  /**
   * @memberof WorkedDays
   * @type {number}
   */
  difference?: number | null;
}

/** Check if a given object implements the WorkedDays interface. */
export function instanceOfWorkedDays(value: object): value is WorkedDays {
  return true;
}

export function WorkedDaysFromJSON(json: any): WorkedDays {
  return WorkedDaysFromJSONTyped(json, false);
}

export function WorkedDaysFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WorkedDays {
  if (json == null) {
    return json;
  }
  return {
    worked: json['worked'] == null ? undefined : json['worked'],
    max: json['max'] == null ? undefined : json['max'],
    difference: json['difference'] == null ? undefined : json['difference']
  };
}

export function WorkedDaysToJSON(json: any): WorkedDays {
  return WorkedDaysToJSONTyped(json, false);
}

export function WorkedDaysToJSONTyped(
  value?: WorkedDays | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    worked: value['worked'],
    max: value['max'],
    difference: value['difference']
  };
}
