import '../globals.css';

import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import { inter } from '@/lib/fonts/fonts';
import Providers from '@/components/shared/Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl">
      <body className={`${inter.variable} antialiased font-sans`}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
