/* tslint:disable */
/* eslint-disable */
/**
 * Easylog No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import * as runtime from '../runtime';
import type { AuthConfigurationsGet200Response } from '../models/index';
import {
  AuthConfigurationsGet200ResponseFromJSON,
  AuthConfigurationsGet200ResponseToJSON
} from '../models/index';

export class AuthenticationApi extends runtime.BaseAPI {
  /**
   * All openidconnect configurations that are enabled on this instance, all
   * authorization code with pkce flow. Get available authentication
   * configurations for this instance
   */
  async authConfigurationsGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthConfigurationsGet200Response>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/auth-configurations`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthConfigurationsGet200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * All openidconnect configurations that are enabled on this instance, all
   * authorization code with pkce flow. Get available authentication
   * configurations for this instance
   */
  async authConfigurationsGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthConfigurationsGet200Response> {
    const response = await this.authConfigurationsGetRaw(initOverrides);
    return await response.value();
  }
}
