/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatCreateInput
 */
export interface ChatCreateInput {
    /**
     * 
     * @type {string}
     * @memberof ChatCreateInput
     */
    external_id?: string | null;
}

/**
 * Check if a given object implements the ChatCreateInput interface.
 */
export function instanceOfChatCreateInput(value: object): value is ChatCreateInput {
    return true;
}

export function ChatCreateInputFromJSON(json: any): ChatCreateInput {
    return ChatCreateInputFromJSONTyped(json, false);
}

export function ChatCreateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCreateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'external_id': json['external_id'] == null ? undefined : json['external_id'],
    };
}

export function ChatCreateInputToJSON(json: any): ChatCreateInput {
    return ChatCreateInputToJSONTyped(json, false);
}

export function ChatCreateInputToJSONTyped(value?: ChatCreateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external_id': value['external_id'],
    };
}

