/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface HealthResponse
 */
export interface HealthResponse {
  [key: string]: any | any;
  /**
   * @memberof HealthResponse
   * @type {string}
   */
  api: HealthResponseApiEnum;
  /**
   * @memberof HealthResponse
   * @type {string}
   */
  main_db: HealthResponseMainDbEnum;
  /**
   * @memberof HealthResponse
   * @type {string}
   */
  easylog_db: HealthResponseEasylogDbEnum;
  /**
   * @memberof HealthResponse
   * @type {string}
   */
  neo4j: HealthResponseNeo4jEnum;
}

/** @export */
export const HealthResponseApiEnum = {
  Healthy: 'healthy'
} as const;
export type HealthResponseApiEnum =
  (typeof HealthResponseApiEnum)[keyof typeof HealthResponseApiEnum];

/** @export */
export const HealthResponseMainDbEnum = {
  Healthy: 'healthy',
  Unhealthy: 'unhealthy'
} as const;
export type HealthResponseMainDbEnum =
  (typeof HealthResponseMainDbEnum)[keyof typeof HealthResponseMainDbEnum];

/** @export */
export const HealthResponseEasylogDbEnum = {
  Healthy: 'healthy',
  Unhealthy: 'unhealthy'
} as const;
export type HealthResponseEasylogDbEnum =
  (typeof HealthResponseEasylogDbEnum)[keyof typeof HealthResponseEasylogDbEnum];

/** @export */
export const HealthResponseNeo4jEnum = {
  Healthy: 'healthy',
  Unhealthy: 'unhealthy'
} as const;
export type HealthResponseNeo4jEnum =
  (typeof HealthResponseNeo4jEnum)[keyof typeof HealthResponseNeo4jEnum];

/** Check if a given object implements the HealthResponse interface. */
export function instanceOfHealthResponse(
  value: object
): value is HealthResponse {
  if (!('api' in value) || value['api'] === undefined) return false;
  if (!('main_db' in value) || value['main_db'] === undefined) return false;
  if (!('easylog_db' in value) || value['easylog_db'] === undefined)
    return false;
  if (!('neo4j' in value) || value['neo4j'] === undefined) return false;
  return true;
}

export function HealthResponseFromJSON(json: any): HealthResponse {
  return HealthResponseFromJSONTyped(json, false);
}

export function HealthResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): HealthResponse {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    api: json['api'],
    main_db: json['main_db'],
    easylog_db: json['easylog_db'],
    neo4j: json['neo4j']
  };
}

export function HealthResponseToJSON(json: any): HealthResponse {
  return HealthResponseToJSONTyped(json, false);
}

export function HealthResponseToJSONTyped(
  value?: HealthResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    api: value['api'],
    main_db: value['main_db'],
    easylog_db: value['easylog_db'],
    neo4j: value['neo4j']
  };
}
