/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface ImageContent
 */
export interface ImageContent {
  /**
   * The ID of the content.
   *
   * @memberof ImageContent
   * @type {string}
   */
  id: string;
  /**
   * @memberof ImageContent
   * @type {string}
   */
  type?: ImageContentTypeEnum;
  /**
   * The URL of the image.
   *
   * @memberof ImageContent
   * @type {string}
   */
  image_url: string;
}

/** @export */
export const ImageContentTypeEnum = {
  Image: 'image'
} as const;
export type ImageContentTypeEnum =
  (typeof ImageContentTypeEnum)[keyof typeof ImageContentTypeEnum];

/** Check if a given object implements the ImageContent interface. */
export function instanceOfImageContent(value: object): value is ImageContent {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('image_url' in value) || value['image_url'] === undefined) return false;
  return true;
}

export function ImageContentFromJSON(json: any): ImageContent {
  return ImageContentFromJSONTyped(json, false);
}

export function ImageContentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ImageContent {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    type: json['type'] == null ? undefined : json['type'],
    image_url: json['image_url']
  };
}

export function ImageContentToJSON(json: any): ImageContent {
  return ImageContentToJSONTyped(json, false);
}

export function ImageContentToJSONTyped(
  value?: ImageContent | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    type: value['type'],
    image_url: value['image_url']
  };
}
