/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface MessageCreateInputFileContent
 */
export interface MessageCreateInputFileContent {
  /**
   * @memberof MessageCreateInputFileContent
   * @type {string}
   */
  type?: MessageCreateInputFileContentTypeEnum;
  /**
   * @memberof MessageCreateInputFileContent
   * @type {string}
   */
  file_data: string;
  /**
   * @memberof MessageCreateInputFileContent
   * @type {string}
   */
  file_name: string;
}

/** @export */
export const MessageCreateInputFileContentTypeEnum = {
  File: 'file'
} as const;
export type MessageCreateInputFileContentTypeEnum =
  (typeof MessageCreateInputFileContentTypeEnum)[keyof typeof MessageCreateInputFileContentTypeEnum];

/**
 * Check if a given object implements the MessageCreateInputFileContent
 * interface.
 */
export function instanceOfMessageCreateInputFileContent(
  value: object
): value is MessageCreateInputFileContent {
  if (!('file_data' in value) || value['file_data'] === undefined) return false;
  if (!('file_name' in value) || value['file_name'] === undefined) return false;
  return true;
}

export function MessageCreateInputFileContentFromJSON(
  json: any
): MessageCreateInputFileContent {
  return MessageCreateInputFileContentFromJSONTyped(json, false);
}

export function MessageCreateInputFileContentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MessageCreateInputFileContent {
  if (json == null) {
    return json;
  }
  return {
    type: json['type'] == null ? undefined : json['type'],
    file_data: json['file_data'],
    file_name: json['file_name']
  };
}

export function MessageCreateInputFileContentToJSON(
  json: any
): MessageCreateInputFileContent {
  return MessageCreateInputFileContentToJSONTyped(json, false);
}

export function MessageCreateInputFileContentToJSONTyped(
  value?: MessageCreateInputFileContent | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value['type'],
    file_data: value['file_data'],
    file_name: value['file_name']
  };
}
