/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MessageContentFormat = {
    Image: 'image',
    Chart: 'chart',
    Unknown: 'unknown'
} as const;
export type MessageContentFormat = typeof MessageContentFormat[keyof typeof MessageContentFormat];


export function instanceOfMessageContentFormat(value: any): boolean {
    for (const key in MessageContentFormat) {
        if (Object.prototype.hasOwnProperty.call(MessageContentFormat, key)) {
            if (MessageContentFormat[key as keyof typeof MessageContentFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MessageContentFormatFromJSON(json: any): MessageContentFormat {
    return MessageContentFormatFromJSONTyped(json, false);
}

export function MessageContentFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageContentFormat {
    return json as MessageContentFormat;
}

export function MessageContentFormatToJSON(value?: MessageContentFormat | null): any {
    return value as any;
}

export function MessageContentFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): MessageContentFormat {
    return value as MessageContentFormat;
}

