/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageCreateInputTextContent } from './message-create-input-text-content';
import {
  MessageCreateInputTextContentFromJSON,
  MessageCreateInputTextContentFromJSONTyped,
  MessageCreateInputTextContentToJSON,
  MessageCreateInputTextContentToJSONTyped
} from './message-create-input-text-content';
import type { MessageCreateInputFileContent } from './message-create-input-file-content';
import {
  MessageCreateInputFileContentFromJSON,
  MessageCreateInputFileContentFromJSONTyped,
  MessageCreateInputFileContentToJSON,
  MessageCreateInputFileContentToJSONTyped
} from './message-create-input-file-content';
import type { MessageCreateInputImageContent } from './message-create-input-image-content';
import {
  MessageCreateInputImageContentFromJSON,
  MessageCreateInputImageContentFromJSONTyped,
  MessageCreateInputImageContentToJSON,
  MessageCreateInputImageContentToJSONTyped
} from './message-create-input-image-content';

/**
 * @export
 * @interface MessageCreateInputContentInner
 */
export interface MessageCreateInputContentInner {
  /**
   * @memberof MessageCreateInputContentInner
   * @type {string}
   */
  type?: MessageCreateInputContentInnerTypeEnum;
  /**
   * @memberof MessageCreateInputContentInner
   * @type {string}
   */
  file_data: string;
  /**
   * @memberof MessageCreateInputContentInner
   * @type {string}
   */
  file_name: string;
  /**
   * @memberof MessageCreateInputContentInner
   * @type {string}
   */
  image_url: string;
  /**
   * @memberof MessageCreateInputContentInner
   * @type {string}
   */
  text: string;
}

/** @export */
export const MessageCreateInputContentInnerTypeEnum = {
  File: 'file',
  Image: 'image',
  Text: 'text'
} as const;
export type MessageCreateInputContentInnerTypeEnum =
  (typeof MessageCreateInputContentInnerTypeEnum)[keyof typeof MessageCreateInputContentInnerTypeEnum];

/**
 * Check if a given object implements the MessageCreateInputContentInner
 * interface.
 */
export function instanceOfMessageCreateInputContentInner(
  value: object
): value is MessageCreateInputContentInner {
  if (!('file_data' in value) || value['file_data'] === undefined) return false;
  if (!('file_name' in value) || value['file_name'] === undefined) return false;
  if (!('image_url' in value) || value['image_url'] === undefined) return false;
  if (!('text' in value) || value['text'] === undefined) return false;
  return true;
}

export function MessageCreateInputContentInnerFromJSON(
  json: any
): MessageCreateInputContentInner {
  return MessageCreateInputContentInnerFromJSONTyped(json, false);
}

export function MessageCreateInputContentInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MessageCreateInputContentInner {
  if (json == null) {
    return json;
  }
  return {
    type: json['type'] == null ? undefined : json['type'],
    file_data: json['file_data'],
    file_name: json['file_name'],
    image_url: json['image_url'],
    text: json['text']
  };
}

export function MessageCreateInputContentInnerToJSON(
  json: any
): MessageCreateInputContentInner {
  return MessageCreateInputContentInnerToJSONTyped(json, false);
}

export function MessageCreateInputContentInnerToJSONTyped(
  value?: MessageCreateInputContentInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value['type'],
    file_data: value['file_data'],
    file_name: value['file_name'],
    image_url: value['image_url'],
    text: value['text']
  };
}
