/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/** @export */
export const MessageContentType = {
  Text: 'text',
  Image: 'image',
  File: 'file',
  ToolUse: 'tool_use',
  ToolResult: 'tool_result'
} as const;
export type MessageContentType =
  (typeof MessageContentType)[keyof typeof MessageContentType];

export function instanceOfMessageContentType(value: any): boolean {
  for (const key in MessageContentType) {
    if (Object.prototype.hasOwnProperty.call(MessageContentType, key)) {
      if (
        MessageContentType[key as keyof typeof MessageContentType] === value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function MessageContentTypeFromJSON(json: any): MessageContentType {
  return MessageContentTypeFromJSONTyped(json, false);
}

export function MessageContentTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MessageContentType {
  return json as MessageContentType;
}

export function MessageContentTypeToJSON(
  value?: MessageContentType | null
): any {
  return value as any;
}

export function MessageContentTypeToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean
): MessageContentType {
  return value as MessageContentType;
}
