/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface MessageCreateInputImageContent
 */
export interface MessageCreateInputImageContent {
  /**
   * @memberof MessageCreateInputImageContent
   * @type {string}
   */
  type?: MessageCreateInputImageContentTypeEnum;
  /**
   * @memberof MessageCreateInputImageContent
   * @type {string}
   */
  image_url: string;
}

/** @export */
export const MessageCreateInputImageContentTypeEnum = {
  Image: 'image'
} as const;
export type MessageCreateInputImageContentTypeEnum =
  (typeof MessageCreateInputImageContentTypeEnum)[keyof typeof MessageCreateInputImageContentTypeEnum];

/**
 * Check if a given object implements the MessageCreateInputImageContent
 * interface.
 */
export function instanceOfMessageCreateInputImageContent(
  value: object
): value is MessageCreateInputImageContent {
  if (!('image_url' in value) || value['image_url'] === undefined) return false;
  return true;
}

export function MessageCreateInputImageContentFromJSON(
  json: any
): MessageCreateInputImageContent {
  return MessageCreateInputImageContentFromJSONTyped(json, false);
}

export function MessageCreateInputImageContentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MessageCreateInputImageContent {
  if (json == null) {
    return json;
  }
  return {
    type: json['type'] == null ? undefined : json['type'],
    image_url: json['image_url']
  };
}

export function MessageCreateInputImageContentToJSON(
  json: any
): MessageCreateInputImageContent {
  return MessageCreateInputImageContentToJSONTyped(json, false);
}

export function MessageCreateInputImageContentToJSONTyped(
  value?: MessageCreateInputImageContent | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value['type'],
    image_url: value['image_url']
  };
}
