/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { Message } from './message';
import {
  MessageFromJSON,
  MessageFromJSONTyped,
  MessageToJSON,
  MessageToJSONTyped
} from './message';

/**
 * @export
 * @interface PaginationMessage
 */
export interface PaginationMessage {
  /**
   * @memberof PaginationMessage
   * @type {Message[]}
   */
  data: Array<Message>;
  /**
   * @memberof PaginationMessage
   * @type {number}
   */
  limit: number;
  /**
   * @memberof PaginationMessage
   * @type {number}
   */
  offset: number;
}

/** Check if a given object implements the PaginationMessage interface. */
export function instanceOfPaginationMessage(
  value: object
): value is PaginationMessage {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('limit' in value) || value['limit'] === undefined) return false;
  if (!('offset' in value) || value['offset'] === undefined) return false;
  return true;
}

export function PaginationMessageFromJSON(json: any): PaginationMessage {
  return PaginationMessageFromJSONTyped(json, false);
}

export function PaginationMessageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginationMessage {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(MessageFromJSON),
    limit: json['limit'],
    offset: json['offset']
  };
}

export function PaginationMessageToJSON(json: any): PaginationMessage {
  return PaginationMessageToJSONTyped(json, false);
}

export function PaginationMessageToJSONTyped(
  value?: PaginationMessage | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(MessageToJSON),
    limit: value['limit'],
    offset: value['offset']
  };
}
