/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageResponse } from './MessageResponse';
import {
  MessageResponseFromJSON,
  MessageResponseFromJSONTyped,
  MessageResponseToJSON,
  MessageResponseToJSONTyped
} from './MessageResponse';

/**
 * @export
 * @interface PaginationMessageResponse
 */
export interface PaginationMessageResponse {
  /**
   * @memberof PaginationMessageResponse
   * @type {MessageResponse[]}
   */
  data: Array<MessageResponse>;
  /**
   * @memberof PaginationMessageResponse
   * @type {number}
   */
  limit: number;
  /**
   * @memberof PaginationMessageResponse
   * @type {number}
   */
  offset: number;
}

/** Check if a given object implements the PaginationMessageResponse interface. */
export function instanceOfPaginationMessageResponse(
  value: object
): value is PaginationMessageResponse {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('limit' in value) || value['limit'] === undefined) return false;
  if (!('offset' in value) || value['offset'] === undefined) return false;
  return true;
}

export function PaginationMessageResponseFromJSON(
  json: any
): PaginationMessageResponse {
  return PaginationMessageResponseFromJSONTyped(json, false);
}

export function PaginationMessageResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginationMessageResponse {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(MessageResponseFromJSON),
    limit: json['limit'],
    offset: json['offset']
  };
}

export function PaginationMessageResponseToJSON(
  json: any
): PaginationMessageResponse {
  return PaginationMessageResponseToJSONTyped(json, false);
}

export function PaginationMessageResponseToJSONTyped(
  value?: PaginationMessageResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(MessageResponseToJSON),
    limit: value['limit'],
    offset: value['offset']
  };
}
