/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PDFContent
 */
export interface PDFContent {
    /**
     * 
     * @type {string}
     * @memberof PDFContent
     */
    type?: PDFContentTypeEnum;
    /**
     * The base64 encoded PDF data, without any prefixes like `data:application/pdf;base64,`, for example: `iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==`
     * @type {string}
     * @memberof PDFContent
     */
    content: string;
}


/**
 * @export
 */
export const PDFContentTypeEnum = {
    Pdf: 'pdf'
} as const;
export type PDFContentTypeEnum = typeof PDFContentTypeEnum[keyof typeof PDFContentTypeEnum];


/**
 * Check if a given object implements the PDFContent interface.
 */
export function instanceOfPDFContent(value: object): value is PDFContent {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function PDFContentFromJSON(json: any): PDFContent {
    return PDFContentFromJSONTyped(json, false);
}

export function PDFContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PDFContent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'content': json['content'],
    };
}

export function PDFContentToJSON(json: any): PDFContent {
    return PDFContentToJSONTyped(json, false);
}

export function PDFContentToJSONTyped(value?: PDFContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'content': value['content'],
    };
}

