/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface TextContent
 */
export interface TextContent {
  /**
   * The ID of the content.
   *
   * @memberof TextContent
   * @type {string}
   */
  id: string;
  /**
   * @memberof TextContent
   * @type {string}
   */
  type?: TextContentTypeEnum;
  /**
   * The content of the message.
   *
   * @memberof TextContent
   * @type {string}
   */
  text: string;
}

/** @export */
export const TextContentTypeEnum = {
  Text: 'text'
} as const;
export type TextContentTypeEnum =
  (typeof TextContentTypeEnum)[keyof typeof TextContentTypeEnum];

/** Check if a given object implements the TextContent interface. */
export function instanceOfTextContent(value: object): value is TextContent {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('text' in value) || value['text'] === undefined) return false;
  return true;
}

export function TextContentFromJSON(json: any): TextContent {
  return TextContentFromJSONTyped(json, false);
}

export function TextContentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TextContent {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    type: json['type'] == null ? undefined : json['type'],
    text: json['text']
  };
}

export function TextContentToJSON(json: any): TextContent {
  return TextContentToJSONTyped(json, false);
}

export function TextContentToJSONTyped(
  value?: TextContent | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    type: value['type'],
    text: value['text']
  };
}
