/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageResponse } from './MessageResponse';
import {
  MessageResponseFromJSON,
  MessageResponseFromJSONTyped,
  MessageResponseToJSON,
  MessageResponseToJSONTyped
} from './MessageResponse';

/**
 * @export
 * @interface ThreadResponse
 */
export interface ThreadResponse {
  /**
   * @memberof ThreadResponse
   * @type {string}
   */
  id: string;
  /**
   * @memberof ThreadResponse
   * @type {string}
   */
  external_id: string | null;
  /**
   * @memberof ThreadResponse
   * @type {Date}
   */
  created_at: Date;
  /**
   * @memberof ThreadResponse
   * @type {Date}
   */
  updated_at: Date;
  /**
   * @memberof ThreadResponse
   * @type {object}
   */
  metadata: object;
  /**
   * @memberof ThreadResponse
   * @type {MessageResponse[]}
   */
  messages: Array<MessageResponse>;
}

/** Check if a given object implements the ThreadResponse interface. */
export function instanceOfThreadResponse(
  value: object
): value is ThreadResponse {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('external_id' in value) || value['external_id'] === undefined)
    return false;
  if (!('created_at' in value) || value['created_at'] === undefined)
    return false;
  if (!('updated_at' in value) || value['updated_at'] === undefined)
    return false;
  if (!('metadata' in value) || value['metadata'] === undefined) return false;
  if (!('messages' in value) || value['messages'] === undefined) return false;
  return true;
}

export function ThreadResponseFromJSON(json: any): ThreadResponse {
  return ThreadResponseFromJSONTyped(json, false);
}

export function ThreadResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ThreadResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    external_id: json['external_id'],
    created_at: new Date(json['created_at']),
    updated_at: new Date(json['updated_at']),
    metadata: json['metadata'],
    messages: (json['messages'] as Array<any>).map(MessageResponseFromJSON)
  };
}

export function ThreadResponseToJSON(json: any): ThreadResponse {
  return ThreadResponseToJSONTyped(json, false);
}

export function ThreadResponseToJSONTyped(
  value?: ThreadResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    external_id: value['external_id'],
    created_at: value['created_at'].toISOString(),
    updated_at: value['updated_at'].toISOString(),
    metadata: value['metadata'],
    messages: (value['messages'] as Array<any>).map(MessageResponseToJSON)
  };
}
