/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface ThreadCreateInput
 */
export interface ThreadCreateInput {
  /**
   * @memberof ThreadCreateInput
   * @type {string}
   */
  external_id?: string | null;
}

/** Check if a given object implements the ThreadCreateInput interface. */
export function instanceOfThreadCreateInput(
  value: object
): value is ThreadCreateInput {
  return true;
}

export function ThreadCreateInputFromJSON(json: any): ThreadCreateInput {
  return ThreadCreateInputFromJSONTyped(json, false);
}

export function ThreadCreateInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ThreadCreateInput {
  if (json == null) {
    return json;
  }
  return {
    external_id: json['external_id'] == null ? undefined : json['external_id']
  };
}

export function ThreadCreateInputToJSON(json: any): ThreadCreateInput {
  return ThreadCreateInputToJSONTyped(json, false);
}

export function ThreadCreateInputToJSONTyped(
  value?: ThreadCreateInput | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    external_id: value['external_id']
  };
}
