/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface ToolResultDeltaContent
 */
export interface ToolResultDeltaContent {
  /**
   * @memberof ToolResultDeltaContent
   * @type {string}
   */
  type?: ToolResultDeltaContentTypeEnum;
  /**
   * The ID of the tool use.
   *
   * @memberof ToolResultDeltaContent
   * @type {string}
   */
  tool_use_id: string;
  /**
   * The result of the tool.
   *
   * @memberof ToolResultDeltaContent
   * @type {string}
   */
  content: string;
  /**
   * The format of the content.
   *
   * @memberof ToolResultDeltaContent
   * @type {string}
   */
  content_format?: ToolResultDeltaContentContentFormatEnum;
  /**
   * Whether the tool result is an error.
   *
   * @memberof ToolResultDeltaContent
   * @type {boolean}
   */
  is_error?: boolean;
}

/** @export */
export const ToolResultDeltaContentTypeEnum = {
  ToolResultDelta: 'tool_result_delta'
} as const;
export type ToolResultDeltaContentTypeEnum =
  (typeof ToolResultDeltaContentTypeEnum)[keyof typeof ToolResultDeltaContentTypeEnum];

/** @export */
export const ToolResultDeltaContentContentFormatEnum = {
  Image: 'image',
  Chart: 'chart',
  Unknown: 'unknown'
} as const;
export type ToolResultDeltaContentContentFormatEnum =
  (typeof ToolResultDeltaContentContentFormatEnum)[keyof typeof ToolResultDeltaContentContentFormatEnum];

/** Check if a given object implements the ToolResultDeltaContent interface. */
export function instanceOfToolResultDeltaContent(
  value: object
): value is ToolResultDeltaContent {
  if (!('tool_use_id' in value) || value['tool_use_id'] === undefined)
    return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  return true;
}

export function ToolResultDeltaContentFromJSON(
  json: any
): ToolResultDeltaContent {
  return ToolResultDeltaContentFromJSONTyped(json, false);
}

export function ToolResultDeltaContentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ToolResultDeltaContent {
  if (json == null) {
    return json;
  }
  return {
    type: json['type'] == null ? undefined : json['type'],
    tool_use_id: json['tool_use_id'],
    content: json['content'],
    content_format:
      json['content_format'] == null ? undefined : json['content_format'],
    is_error: json['is_error'] == null ? undefined : json['is_error']
  };
}

export function ToolResultDeltaContentToJSON(
  json: any
): ToolResultDeltaContent {
  return ToolResultDeltaContentToJSONTyped(json, false);
}

export function ToolResultDeltaContentToJSONTyped(
  value?: ToolResultDeltaContent | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value['type'],
    tool_use_id: value['tool_use_id'],
    content: value['content'],
    content_format: value['content_format'],
    is_error: value['is_error']
  };
}
