/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/** @export */
export const WidgetType = {
  Image: 'image',
  Chart: 'chart'
} as const;
export type WidgetType = (typeof WidgetType)[keyof typeof WidgetType];

export function instanceOfWidgetType(value: any): boolean {
  for (const key in WidgetType) {
    if (Object.prototype.hasOwnProperty.call(WidgetType, key)) {
      if (WidgetType[key as keyof typeof WidgetType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function WidgetTypeFromJSON(json: any): WidgetType {
  return WidgetTypeFromJSONTyped(json, false);
}

export function WidgetTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WidgetType {
  return json as WidgetType;
}

export function WidgetTypeToJSON(value?: WidgetType | null): any {
  return value as any;
}

export function WidgetTypeToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean
): WidgetType {
  return value as WidgetType;
}
